--- Donia Update interview notifications 08/02/2020
BEGIN TRANSACTION
ALTER TABLE [ERPSettings].[Information] DROP CONSTRAINT [FK_Information_Information]
ALTER TABLE [ERPSettings].[Information] DROP CONSTRAINT [FK_Information_Functionality]
UPDATE [ERPSettings].[Information] SET [FR]=N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur requis pour l''entretien du candidat {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', [EN]=N'{INTERVIEW_CREATOR} has added you as a required interviewer to the interview of the candidate {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', [Type]=N'ADDED_AS_REQUIRED_INTERVIEWER_FOR_CANDIDACY' WHERE [IdInfo]=1000501097
UPDATE [ERPSettings].[Information] SET [FR]=N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour l''entretien du candidat {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', [EN]=N'{INTERVIEW_CREATOR} has added you as a optional interviewer to the interview of the candidate {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', [Type]=N'ADDED_AS_OPTIONAL_INTERVIEWER_FOR_CANDIDACY' WHERE [IdInfo]=1000501098
UPDATE [ERPSettings].[Information] SET [FR]=N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour l''entretien du candidat {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', [EN]=N'{INTERVIEW_CREATOR} has added you as a optional interviewer to the interview of the candidate {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', [Type]=N'DELETED_FROM_INTERVIEWER_LIST_FOR_CANDIDACY' WHERE [IdInfo]=1000501099
GO
SET IDENTITY_INSERT [ERPSettings].[Information] ON
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501246, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/payroll/exit-employee/edit', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur requis pour la réunion de sortie de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a required interviewer to the exit employee meeting of {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_ADD_REQUIRED_INTERVIEWER_FOR_EXIT_EMPLOYEE', N'ADDED_AS_REQUIRED_INTERVIEWER_FOR_EXIT_EMPLOYEE')
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501247, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/payroll/exit-employee/edit', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour la réunion de sortie de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a optional interviewer to the exit employee meeting of NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_ADD_OPTIONAL_INTERVIEWER_FOR_EXIT_EMPLOYEE', N'ADDED_AS_OPTIONAL_INTERVIEWER_FOR_EXIT_EMPLOYEE')
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501248, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/payroll/exit-employee/edit', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour la réunion de sortie de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a optional interviewer  to the exit employee meeting of  NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_DELETE_INTERVIEWER_FOR_EXIT_EMPLOYEE', N'DELETED_FROM_INTERVIEWER_LIST_FOR_EXIT_EMPLOYEE')
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501249, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/rh/review', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur requis pour l''entretien de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a required interviewer to the interview of {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_ADD_REQUIRED_INTERVIEWER_FOR_REVIEW', N'ADDED_AS_REQUIRED_INTERVIEWER_FOR_REVIEW')
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501250, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/rh/review', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour l''entretien de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a optional interviewer to the interview of {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_ADD_OPTIONAL_INTERVIEWER_FOR_REVIEW', N'ADDED_AS_OPTIONAL_INTERVIEWER_FOR_REVIEW')
INSERT INTO [ERPSettings].[Information] ([IdInfo], [IdFunctionality], [URL], [FR], [EN], [AR], [DE], [CH], [ES], [IsMail], [IsNotification], [MailSubject], [IsAcceptedInfo], [IsToManager], [IdInfoParent], [TranslationKey], [Type]) VALUES (1000501251, N'3a396a34-e1f0-4c47-93db-394bc5f4c557', N'/rh/review', N'{INTERVIEW_CREATOR} vous a ajouté en tant qu''intervieweur optionnel pour l''entretien de {NAME} le {INTERVIEW_DATE} à {INTERVIEW_TIME}', N'{INTERVIEW_CREATOR} has added you as a optional interviewer to the interview of {NAME} on {INTERVIEW_DATE} at {INTERVIEW_TIME}', NULL, NULL, NULL, NULL, 0, 0, N'STARK-ERP Notification', 1, 0, NULL, N'NOTIFICATION_DELETE_INTERVIEWER_FOR_REVIEW', N'DELETED_FROM_INTERVIEWER_LIST_FOR_REVIEW')
SET IDENTITY_INSERT [ERPSettings].[Information] OFF
ALTER TABLE [ERPSettings].[Information]
    ADD CONSTRAINT [FK_Information_Information] FOREIGN KEY ([IdInfoParent]) REFERENCES [ERPSettings].[Information] ([IdInfo])
ALTER TABLE [ERPSettings].[Information]
    ADD CONSTRAINT [FK_Information_Functionality] FOREIGN KEY ([IdFunctionality]) REFERENCES [ERPSettings].[Functionality] ([IdFunctionality])
COMMIT TRANSACTION