BEGIN TRANSACTION
ALTER TABLE [Inventory].[ItemWarehouse] DROP CONSTRAINT [FK_ItemWarehouse_Warehouse]
ALTER TABLE [Inventory].[ItemWarehouse] DROP CONSTRAINT [FK_ItemWarehouse_Item]

INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58598, 17, 20, 20000, 6,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58599, 17, 20, 20000, 7,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58600, 17, 20, 20000, 8,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58601, 17, 20, 20000, 4,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58602, 17, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 58603, 17, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104699, 17, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104700, 17, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104701, 17, 20, 20000, 4,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104703, 17, 20, 20000, 0,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104704, 17, 20, 20000, 0,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104705, 17, 20, 20000, 9,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104707, 17, 20, 20000, 7,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104709, 17, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')


INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104712, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104713, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104716, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104717, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104719, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104720, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104721, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104722, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104723, 16, 20, 20000, 1,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104726, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104728, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104729, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104730, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104731, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104732, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104733, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104734, 16, 20, 20000, 2,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104735, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104736, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104737, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104738, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104739, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104740, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104741, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104742, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')
INSERT INTO [Inventory].[ItemWarehouse] ([IdItem], [IdWarehouse], [MinQuantity], [MaxQuantity], [AvailableQuantity], [ReservedQuantity], [OnOrderQuantity], [IsDeleted], [TransactionUserId], [Deleted_Token], [Shelf], [Storage]) VALUES ( 104743, 16, 20, 20000, 3,0, 0, 0, 0, N'', N'', N'')


ALTER TABLE [Inventory].[ItemWarehouse]
    ADD CONSTRAINT [FK_ItemWarehouse_Warehouse] FOREIGN KEY ([IdWarehouse]) REFERENCES [Inventory].[Warehouse] ([Id])
ALTER TABLE [Inventory].[ItemWarehouse]
    ADD CONSTRAINT [FK_ItemWarehouse_Item] FOREIGN KEY ([IdItem]) REFERENCES [Inventory].[Item] ([Id]) ON DELETE CASCADE
COMMIT TRANSACTION