// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Address
    {
        public Address()
        {
            Contact = new HashSet<Contact>();
        }

        public int Id { get; set; }
        public string ZipCode { get; set; }
        public string ExtraAdress { get; set; }
        public int? IdTiers { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string PrincipalAddress { get; set; }
        public string Label { get; set; }
        public int? IdCountry { get; set; }
        public int? IdCompany { get; set; }
        public int? IdCity { get; set; }
        public int? IdOffice { get; set; }
        public int? IdZipCode { get; set; }

        public virtual City IdCityNavigation { get; set; }
        public virtual Company IdCompanyNavigation { get; set; }
        public virtual Country IdCountryNavigation { get; set; }
        public virtual Office IdOfficeNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual ZipCode IdZipCodeNavigation { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
    }
}