// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Attendance
    {
        public int Id { get; set; }
        public int IdSession { get; set; }
        public int IdContract { get; set; }
        public double NumberDaysWorked { get; set; }
        public double NumberDaysPaidLeave { get; set; }
        public double NumberDaysNonPaidLeave { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double MaxNumberOfDaysAllowed { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double AdditionalHourOne { get; set; }
        public double AdditionalHourTwo { get; set; }
        public double AdditionalHourThree { get; set; }
        public double AdditionalHourFour { get; set; }

        public virtual Contract IdContractNavigation { get; set; }
        public virtual Session IdSessionNavigation { get; set; }
    }
}