// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// This table defines which entity uses which axes
    /// </summary>
    public partial class AxisEntity
    {
        public int Id { get; set; }
        /// <summary>
        /// Axis identifier
        /// </summary>
        public int IdAxis { get; set; }
        /// <summary>
        /// Entity identifier
        /// </summary>
        public int IdTableEntity { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public bool? IsRequired { get; set; }

        public virtual Axis IdAxisNavigation { get; set; }
        public virtual Entity IdTableEntityNavigation { get; set; }
    }
}