// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// This table defines value of axis
    /// </summary>
    public partial class AxisValue
    {
        public AxisValue()
        {
            AxisValueRelationShipIdAxisValueNavigation = new HashSet<AxisValueRelationShip>();
            AxisValueRelationShipIdAxisValueParentNavigation = new HashSet<AxisValueRelationShip>();
            EntityAxisValues = new HashSet<EntityAxisValues>();
        }

        /// <summary>
        /// AxisValue identifier
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// AxisValue code
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// AxisValue label
        /// </summary>
        public string Label { get; set; }
        /// <summary>
        /// Axis identifier
        /// </summary>
        public int IdAxis { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Axis IdAxisNavigation { get; set; }
        public virtual ICollection<AxisValueRelationShip> AxisValueRelationShipIdAxisValueNavigation { get; set; }
        public virtual ICollection<AxisValueRelationShip> AxisValueRelationShipIdAxisValueParentNavigation { get; set; }
        public virtual ICollection<EntityAxisValues> EntityAxisValues { get; set; }
    }
}