// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class AxisRelationShip
    {
        public int Id { get; set; }
        public int? IdAxis { get; set; }
        public int? IdAxisParent { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Axis IdAxisNavigation { get; set; }
        public virtual Axis IdAxisParentNavigation { get; set; }
    }
}