// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// Analytical axes table
    /// </summary>
    public partial class Axis
    {
        public Axis()
        {
            AxisEntity = new HashSet<AxisEntity>();
            AxisRelationShipIdAxisNavigation = new HashSet<AxisRelationShip>();
            AxisRelationShipIdAxisParentNavigation = new HashSet<AxisRelationShip>();
            AxisValue = new HashSet<AxisValue>();
        }

        /// <summary>
        /// Axis Identifier
        /// </summary>
        public int Id { get; set; }
        public int? Rank { get; set; }
        /// <summary>
        /// Axis code
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Axis label
        /// </summary>
        public string Label { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Fr { get; set; }
        public string Ar { get; set; }
        public string En { get; set; }
        public string De { get; set; }
        public string Ch { get; set; }
        public string Es { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<AxisEntity> AxisEntity { get; set; }
        public virtual ICollection<AxisRelationShip> AxisRelationShipIdAxisNavigation { get; set; }
        public virtual ICollection<AxisRelationShip> AxisRelationShipIdAxisParentNavigation { get; set; }
        public virtual ICollection<AxisValue> AxisValue { get; set; }
    }
}