// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class BankAccount
    {
        public BankAccount()
        {
            Document = new HashSet<Document>();
            PaymentSlip = new HashSet<PaymentSlip>();
            Project = new HashSet<Project>();
            Reconciliation = new HashSet<Reconciliation>();
            Settlement = new HashSet<Settlement>();
            TransferOrder = new HashSet<TransferOrder>();
        }

        public int Id { get; set; }
        public string Rib { get; set; }
        public string Iban { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string Code { get; set; }
        public string Agency { get; set; }
        public string Locality { get; set; }
        public string DeletedToken { get; set; }
        public string Bic { get; set; }
        public double InitialBalance { get; set; }
        public double CurrentBalance { get; set; }
        public int IdBank { get; set; }
        public string Entitled { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Pic { get; set; }
        public int? TypeAccount { get; set; }
        public string ZipCode { get; set; }
        public int IdCurrency { get; set; }
        public int? IdCountry { get; set; }
        public int? IdCity { get; set; }

        public virtual Bank IdBankNavigation { get; set; }
        public virtual City IdCityNavigation { get; set; }
        public virtual Country IdCountryNavigation { get; set; }
        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<PaymentSlip> PaymentSlip { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Reconciliation> Reconciliation { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
        public virtual ICollection<TransferOrder> TransferOrder { get; set; }
    }
}