// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Bank
    {
        public Bank()
        {
            BankAccount = new HashSet<BankAccount>();
            BankAgency = new HashSet<BankAgency>();
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string AttachmentUrl { get; set; }
        public string WebSite { get; set; }
        public int IdCountry { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdPhone { get; set; }

        public virtual Country IdCountryNavigation { get; set; }
        public virtual Phone IdPhoneNavigation { get; set; }
        public virtual ICollection<BankAccount> BankAccount { get; set; }
        public virtual ICollection<BankAgency> BankAgency { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}