// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class BenefitInKind
    {
        public BenefitInKind()
        {
            ContractBenefitInKind = new HashSet<ContractBenefitInKind>();
            OfferBenefitInKind = new HashSet<OfferBenefitInKind>();
            PayslipDetails = new HashSet<PayslipDetails>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? IdCnss { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public bool IsTaxable { get; set; }
        public bool DependNumberDaysWorked { get; set; }

        public virtual Cnss IdCnssNavigation { get; set; }
        public virtual ICollection<ContractBenefitInKind> ContractBenefitInKind { get; set; }
        public virtual ICollection<OfferBenefitInKind> OfferBenefitInKind { get; set; }
        public virtual ICollection<PayslipDetails> PayslipDetails { get; set; }
    }
}