// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class BillingEmployee
    {
        public int Id { get; set; }
        public int IdBillingSession { get; set; }
        public int IdEmployee { get; set; }
        public int IdTimeSheet { get; set; }
        public int IdProject { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public bool IsChecked { get; set; }

        public virtual BillingSession IdBillingSessionNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Project IdProjectNavigation { get; set; }
        public virtual TimeSheet IdTimeSheetNavigation { get; set; }
    }
}