// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class BillingSession
    {
        public BillingSession()
        {
            BillingEmployee = new HashSet<BillingEmployee>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime Month { get; set; }
        public int State { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public int? NumberOfNotGeneratedDocuments { get; set; }

        public virtual ICollection<BillingEmployee> BillingEmployee { get; set; }
    }
}