// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Candidate
    {
        public Candidate()
        {
            Candidacy = new HashSet<Candidacy>();
            CurriculumVitae = new HashSet<CurriculumVitae>();
            Qualification = new HashSet<Qualification>();
        }

        public int Id { get; set; }
        public int Sex { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Cin { get; set; }
        public bool IsForeign { get; set; }
        public int? IdEmployee { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string LinkedIn { get; set; }
        public int? IdCitizenship { get; set; }
        public DateTime CreationDate { get; set; }
        public int? IdCreationUser { get; set; }
        public int? IdOffice { get; set; }
        public DateTime? BirthDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string Facebook { get; set; }
        public string PersonalPhone { get; set; }
        public string ProfessionalPhone { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }

        public virtual Country IdCitizenshipNavigation { get; set; }
        public virtual User IdCreationUserNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual ICollection<Candidacy> Candidacy { get; set; }
        public virtual ICollection<CurriculumVitae> CurriculumVitae { get; set; }
        public virtual ICollection<Qualification> Qualification { get; set; }
    }
}