// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Candidacy
    {
        public Candidacy()
        {
            Interview = new HashSet<Interview>();
            Offer = new HashSet<Offer>();
        }

        public int Id { get; set; }
        public int State { get; set; }
        public int? IdRecruitment { get; set; }
        public int IdCandidate { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime DepositDate { get; set; }
        public int? IdEmail { get; set; }

        public virtual Candidate IdCandidateNavigation { get; set; }
        public virtual Email IdEmailNavigation { get; set; }
        public virtual Recruitment IdRecruitmentNavigation { get; set; }
        public virtual ICollection<Interview> Interview { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
    }
}