// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CashRegister
    {
        public CashRegister()
        {
            FundsTransferIdDestinationCashNavigation = new HashSet<FundsTransfer>();
            FundsTransferIdSourceCashNavigation = new HashSet<FundsTransfer>();
            InverseIdParentCashNavigation = new HashSet<CashRegister>();
            SessionCash = new HashSet<SessionCash>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Address { get; set; }
        public int IdResponsible { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdParentCash { get; set; }
        public int? IdCity { get; set; }
        public int? IdCountry { get; set; }
        public int Status { get; set; }
        public int IdWarehouse { get; set; }
        public string AgentCode { get; set; }

        public virtual City IdCityNavigation { get; set; }
        public virtual Country IdCountryNavigation { get; set; }
        public virtual CashRegister IdParentCashNavigation { get; set; }
        public virtual User IdResponsibleNavigation { get; set; }
        public virtual Warehouse IdWarehouseNavigation { get; set; }
        public virtual ICollection<FundsTransfer> FundsTransferIdDestinationCashNavigation { get; set; }
        public virtual ICollection<FundsTransfer> FundsTransferIdSourceCashNavigation { get; set; }
        public virtual ICollection<CashRegister> InverseIdParentCashNavigation { get; set; }
        public virtual ICollection<SessionCash> SessionCash { get; set; }
    }
}