// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Category
    {
        public Category()
        {
            Active = new HashSet<Active>();
        }

        public int Id { get; set; }
        public int? MinPeriod { get; set; }
        public int? MaxPeriod { get; set; }
        public int? ImmobilisationType { get; set; }
        public string Label { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Active> Active { get; set; }
    }
}