// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class City
    {
        public City()
        {
            Address = new HashSet<Address>();
            BankAccount = new HashSet<BankAccount>();
            CashRegister = new HashSet<CashRegister>();
            Employee = new HashSet<Employee>();
            Tiers = new HashSet<Tiers>();
            ZipCode = new HashSet<ZipCode>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public int? IdCountry { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Country IdCountryNavigation { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<BankAccount> BankAccount { get; set; }
        public virtual ICollection<CashRegister> CashRegister { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Tiers> Tiers { get; set; }
        public virtual ICollection<ZipCode> ZipCode { get; set; }
    }
}