// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Civility
    {
        public int Id { get; set; }
        public string CivilityCode { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? CivilityInt1 { get; set; }
        public int? CivilityInt2 { get; set; }
        public int? CivilityInt3 { get; set; }
        public int? CivilityInt4 { get; set; }
        public int? CivilityInt5 { get; set; }
        public int? CivilityInt6 { get; set; }
        public int? CivilityInt7 { get; set; }
        public int? CivilityInt8 { get; set; }
        public int? CivilityInt9 { get; set; }
        public int? CivilityInt10 { get; set; }
        public bool? CivilityBit1 { get; set; }
        public bool? CivilityBit2 { get; set; }
        public bool? CivilityBit3 { get; set; }
        public bool? CivilityBit4 { get; set; }
        public bool? CivilityBit5 { get; set; }
        public bool? CivilityBit6 { get; set; }
        public bool? CivilityBit7 { get; set; }
        public bool? CivilityBit8 { get; set; }
        public bool? CivilityBit9 { get; set; }
        public bool? CivilityBit10 { get; set; }
        public double? CivilityFloat1 { get; set; }
        public double? CivilityFloat2 { get; set; }
        public double? CivilityFloat3 { get; set; }
        public double? CivilityFloat4 { get; set; }
        public double? CivilityFloat5 { get; set; }
        public double? CivilityFloat6 { get; set; }
        public double? CivilityFloat7 { get; set; }
        public double? CivilityFloat8 { get; set; }
        public double? CivilityFloat9 { get; set; }
        public double? CivilityFloat10 { get; set; }
        public string CivilityVarchar1 { get; set; }
        public string CivilityVarchar2 { get; set; }
        public string CivilityVarchar3 { get; set; }
        public string CivilityVarchar4 { get; set; }
        public string CivilityVarchar5 { get; set; }
        public string CivilityVarchar6 { get; set; }
        public string CivilityVarchar7 { get; set; }
        public string CivilityVarchar8 { get; set; }
        public string CivilityVarchar9 { get; set; }
        public string CivilityVarchar10 { get; set; }
        public DateTime? CivilityDate1 { get; set; }
        public DateTime? CivilityDate2 { get; set; }
        public DateTime? CivilityDate3 { get; set; }
        public DateTime? CivilityDate4 { get; set; }
        public DateTime? CivilityDate5 { get; set; }
        public DateTime? CivilityDate6 { get; set; }
        public DateTime? CivilityDate7 { get; set; }
        public DateTime? CivilityDate8 { get; set; }
        public DateTime? CivilityDate9 { get; set; }
        public DateTime? CivilityDate10 { get; set; }
        public string DeletedToken { get; set; }
    }
}