// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ClaimStatus
    {
        public ClaimStatus()
        {
            Claim = new HashSet<Claim>();
        }

        public int Id { get; set; }
        public int IdStatus { get; set; }
        public string CodeStatus { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public string TranslationCode { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Claim> Claim { get; set; }
    }
}