// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ClaimInteraction
    {
        public int Id { get; set; }
        public int IdClaim { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string TypeInteraction { get; set; }
        public string Description { get; set; }
        public string TranslationCode { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Claim IdClaimNavigation { get; set; }
    }
}