// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ClaimType
    {
        public ClaimType()
        {
            Claim = new HashSet<Claim>();
        }

        public string CodeType { get; set; }
        public string Type { get; set; }
        public string StockOperation { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string TranslationCode { get; set; }

        public virtual ICollection<Claim> Claim { get; set; }
    }
}