// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ClaimTypeRelation
    {
        public int Id { get; set; }
        public string CodeClaimType { get; set; }
        public string CodeClaimTypeAssociated { get; set; }
    }
}