// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Claim
    {
        public Claim()
        {
            ClaimInteraction = new HashSet<ClaimInteraction>();
            StockMovement = new HashSet<StockMovement>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public string Informations { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public bool IsTreated { get; set; }
        public int? IdClaimStatus { get; set; }
        public string ClaimType { get; set; }
        public int? IdWarehouse { get; set; }
        public int? IdItem { get; set; }
        public int? IdClient { get; set; }
        public int? IdContact { get; set; }
        public int? IdFournisseur { get; set; }
        public int? IdDocument { get; set; }
        public int? IdDocumentLine { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? ValidationDate { get; set; }
        public double? ClaimQty { get; set; }
        public int? IdPurchaseDocument { get; set; }
        public int? IdReceiptDocument { get; set; }
        public int? IdSalesDocument { get; set; }
        public int? IdDeliveryDocument { get; set; }
        public double? ClaimMaxQty { get; set; }
        public int? IdSalesAssetDocument { get; set; }
        public int? IdPurchaseAssetDocument { get; set; }
        public bool IsClaimQtyLocked { get; set; }
        public int? IdMovementIn { get; set; }
        public int? IdMovementOut { get; set; }
        public string ReferenceOldDocument { get; set; }

        public virtual ClaimType ClaimTypeNavigation { get; set; }
        public virtual ClaimStatus IdClaimStatusNavigation { get; set; }
        public virtual Tiers IdClientNavigation { get; set; }
        public virtual Contact IdContactNavigation { get; set; }
        public virtual Document IdDeliveryDocumentNavigation { get; set; }
        public virtual DocumentLine IdDocumentLineNavigation { get; set; }
        public virtual Document IdDocumentNavigation { get; set; }
        public virtual Tiers IdFournisseurNavigation { get; set; }
        public virtual Item IdItemNavigation { get; set; }
        public virtual Document IdMovementInNavigation { get; set; }
        public virtual Document IdMovementOutNavigation { get; set; }
        public virtual Document IdPurchaseAssetDocumentNavigation { get; set; }
        public virtual Document IdPurchaseDocumentNavigation { get; set; }
        public virtual Document IdReceiptDocumentNavigation { get; set; }
        public virtual Document IdSalesAssetDocumentNavigation { get; set; }
        public virtual Document IdSalesDocumentNavigation { get; set; }
        public virtual Warehouse IdWarehouseNavigation { get; set; }
        public virtual ICollection<ClaimInteraction> ClaimInteraction { get; set; }
        public virtual ICollection<StockMovement> StockMovement { get; set; }
    }
}