// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ClientDetails
    {
        public string AppId { get; set; }
        public string ResourceIds { get; set; }
        public string AppSecret { get; set; }
        public string Scope { get; set; }
        public string GrantTypes { get; set; }
        public string RedirectUrl { get; set; }
        public string Authorities { get; set; }
        public int? AccessTokenValidity { get; set; }
        public int? RefreshTokenValidity { get; set; }
        public string AdditionalInformation { get; set; }
        public string AutoApproveScopes { get; set; }
    }
}