// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CnssDeclaration
    {
        public CnssDeclaration()
        {
            CnssDeclarationDetails = new HashSet<CnssDeclarationDetails>();
            CnssDeclarationSession = new HashSet<CnssDeclarationSession>();
        }

        public int Id { get; set; }
        public int Trimester { get; set; }
        public int Year { get; set; }
        public DateTime CreationDate { get; set; }
        public double TotalAmount { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdCnss { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public bool? State { get; set; }

        public virtual Cnss IdCnssNavigation { get; set; }
        public virtual ICollection<CnssDeclarationDetails> CnssDeclarationDetails { get; set; }
        public virtual ICollection<CnssDeclarationSession> CnssDeclarationSession { get; set; }
    }
}