// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Cnss
    {
        public Cnss()
        {
            BenefitInKind = new HashSet<BenefitInKind>();
            Bonus = new HashSet<Bonus>();
            CnssDeclaration = new HashSet<CnssDeclaration>();
            Contract = new HashSet<Contract>();
            Offer = new HashSet<Offer>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public double EmployerRate { get; set; }
        public double SalaryRate { get; set; }
        public double WorkAccidentQuota { get; set; }
        public string OperatingCode { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<BenefitInKind> BenefitInKind { get; set; }
        public virtual ICollection<Bonus> Bonus { get; set; }
        public virtual ICollection<CnssDeclaration> CnssDeclaration { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
    }
}