// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CnssDeclarationSession
    {
        public int Id { get; set; }
        public int IdSession { get; set; }
        public int IdCnssDeclaration { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual CnssDeclaration IdCnssDeclarationNavigation { get; set; }
        public virtual Session IdSessionNavigation { get; set; }
    }
}