// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CnssDeclarationDetails
    {
        public int Id { get; set; }
        public int NumberOrder { get; set; }
        public int IdEmployee { get; set; }
        public double FirstMonthValue { get; set; }
        public double SecondMonthValue { get; set; }
        public double ThirdMonthValue { get; set; }
        public double Total { get; set; }
        public int IdCnssDeclaration { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int PageNumber { get; set; }

        public virtual CnssDeclaration IdCnssDeclarationNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
    }
}