// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Codification
    {
        public Codification()
        {
            EntityCodification = new HashSet<EntityCodification>();
            InverseIdCodificationParentNavigation = new HashSet<Codification>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Rank { get; set; }
        public string Path { get; set; }
        public string Format { get; set; }
        public string InitValue { get; set; }
        public int? IdCodificationParent { get; set; }
        public bool? IsCounter { get; set; }
        public int? Step { get; set; }
        public string LastCounterValue { get; set; }
        public int? CounterLength { get; set; }

        public virtual Codification IdCodificationParentNavigation { get; set; }
        public virtual ICollection<EntityCodification> EntityCodification { get; set; }
        public virtual ICollection<Codification> InverseIdCodificationParentNavigation { get; set; }
    }
}