// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Comment
    {
        public int Id { get; set; }
        public int? IdEntityReference { get; set; }
        public int? IdEntityCreated { get; set; }
        public string Message { get; set; }
        public DateTime? CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string EmailCreator { get; set; }

        public virtual Entity IdEntityReferenceNavigation { get; set; }
    }
}