// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Company
    {
        public Company()
        {
            Address = new HashSet<Address>();
            Contact = new HashSet<Contact>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string MatriculeFisc { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CommercialRegister { get; set; }
        public string TaxIdentNumber { get; set; }
        public byte[] Picture { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Siret { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public double? FiscalStamp { get; set; }
        public string Nic { get; set; }
        public int? IdNaf { get; set; }
        public double? Capital { get; set; }
        /// <summary>
        /// Décalage de paye
        /// </summary>
        public string PaymentOffset { get; set; }
        public int? IdAtrate { get; set; }
        /// <summary>
        /// Heures de références
        /// </summary>
        public double? HeuRef { get; set; }
        /// <summary>
        /// Mode de régularisation
        /// </summary>
        public string RegularisationMode { get; set; }
        public int? IdCurrency { get; set; }
        public string Culture { get; set; }
        public string DeletedToken { get; set; }
        public string AttachmentUrl { get; set; }
        public byte[] DataLogoCompany { get; set; }
        public string VatNumber { get; set; }
        public string CnssAffiliation { get; set; }
        public bool? TimeSheetPerHalfDay { get; set; }
        public string Category { get; set; }
        public string SecondaryEstablishment { get; set; }
        public bool PayDependOnTimesheet { get; set; }
        public double? DaysOfWork { get; set; }
        public int ActivityArea { get; set; }
        public string ActivitySector { get; set; }
        public bool? WithholdingTax { get; set; }
        public bool? AllowEditionItemDesignation { get; set; }
        public bool AutomaticCandidateMailSending { get; set; }
        public string DaysWorkedInTheWeek { get; set; }
        public int? IdDefaultTax { get; set; }
        public bool? AllowRelationSupplierItems { get; set; }
        public bool? NoteIsRequired { get; set; }

        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual Taxe IdDefaultTaxNavigation { get; set; }
        public virtual PurchaseSettings PurchaseSettings { get; set; }
        public virtual SaleSettings SaleSettings { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
    }
}