// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ConstantRate
    {
        public ConstantRate()
        {
            ConstantRateValidityPeriod = new HashSet<ConstantRateValidityPeriod>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdRuleUniqueReference { get; set; }

        public virtual RuleUniqueReference IdRuleUniqueReferenceNavigation { get; set; }
        public virtual ICollection<ConstantRateValidityPeriod> ConstantRateValidityPeriod { get; set; }
    }
}