// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ConstantRateValidityPeriod
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public double? SalaryRate { get; set; }
        public double? EmployerRate { get; set; }
        public int IdConstantRate { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ConstantRate IdConstantRateNavigation { get; set; }
    }
}