// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ContractBonus
    {
        public int Id { get; set; }
        public int IdBonus { get; set; }
        public int IdContract { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double? Value { get; set; }
        public DateTime ValidityStartDate { get; set; }
        public DateTime? ValidityEndDate { get; set; }
        public int? State { get; set; }

        public virtual Bonus IdBonusNavigation { get; set; }
        public virtual Contract IdContractNavigation { get; set; }
    }
}