// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Contract
    {
        public Contract()
        {
            Attendance = new HashSet<Attendance>();
            BaseSalary = new HashSet<BaseSalary>();
            ContractAdvantage = new HashSet<ContractAdvantage>();
            ContractBenefitInKind = new HashSet<ContractBenefitInKind>();
            ContractBonus = new HashSet<ContractBonus>();
            Payslip = new HashSet<Payslip>();
            SessionBonus = new HashSet<SessionBonus>();
            SessionContract = new HashSet<SessionContract>();
            SessionLoanInstallment = new HashSet<SessionLoanInstallment>();
        }

        public int Id { get; set; }
        public string ContractReference { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double? WorkingTime { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdEmployee { get; set; }
        public int IdSalaryStructure { get; set; }
        public int IdCnss { get; set; }
        public string ContractAttached { get; set; }
        public int IdContractType { get; set; }
        public int? State { get; set; }
        public bool? ThirteenthMonthBonus { get; set; }
        public double? MealVoucher { get; set; }
        public bool? AvailableCar { get; set; }
        public bool? AvailableHouse { get; set; }
        public int? CommissionType { get; set; }
        public double? CommissionValue { get; set; }

        public virtual Cnss IdCnssNavigation { get; set; }
        public virtual ContractType IdContractTypeNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual SalaryStructure IdSalaryStructureNavigation { get; set; }
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<BaseSalary> BaseSalary { get; set; }
        public virtual ICollection<ContractAdvantage> ContractAdvantage { get; set; }
        public virtual ICollection<ContractBenefitInKind> ContractBenefitInKind { get; set; }
        public virtual ICollection<ContractBonus> ContractBonus { get; set; }
        public virtual ICollection<Payslip> Payslip { get; set; }
        public virtual ICollection<SessionBonus> SessionBonus { get; set; }
        public virtual ICollection<SessionContract> SessionContract { get; set; }
        public virtual ICollection<SessionLoanInstallment> SessionLoanInstallment { get; set; }
    }
}