// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Contact
    {
        public Contact()
        {
            Claim = new HashSet<Claim>();
            ContactTypeDocument = new HashSet<ContactTypeDocument>();
            DateToRemember = new HashSet<DateToRemember>();
            Document = new HashSet<Document>();
            Phone = new HashSet<Phone>();
            PriceRequestDetail = new HashSet<PriceRequestDetail>();
            Project = new HashSet<Project>();
        }

        public int Id { get; set; }
        public int? IdTiers { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public byte[] Picture { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public int? IdVille { get; set; }
        public string Adress { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int Type { get; set; }
        public string DeletedToken { get; set; }
        public string Fonction { get; set; }
        public int? IdCompany { get; set; }
        public string HomePhone { get; set; }
        public string OtherPhone { get; set; }
        public string AssistantPhone { get; set; }
        public string AssistantName { get; set; }
        public string Linkedin { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string UrlPicture { get; set; }
        public string ContactType { get; set; }
        public string Prefix { get; set; }
        public string Classification { get; set; }
        public string MapLocation { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Description { get; set; }
        public int? IdAddress { get; set; }
        public string Label { get; set; }
        public int? IdAgency { get; set; }
        public int? IdOffice { get; set; }
        public bool WasLead { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual Address IdAddressNavigation { get; set; }
        public virtual BankAgency IdAgencyNavigation { get; set; }
        public virtual Company IdCompanyNavigation { get; set; }
        public virtual Office IdOfficeNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual ICollection<Claim> Claim { get; set; }
        public virtual ICollection<ContactTypeDocument> ContactTypeDocument { get; set; }
        public virtual ICollection<DateToRemember> DateToRemember { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<Phone> Phone { get; set; }
        public virtual ICollection<PriceRequestDetail> PriceRequestDetail { get; set; }
        public virtual ICollection<Project> Project { get; set; }
    }
}