// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ContactTypeDocument
    {
        public int Id { get; set; }
        public int? IdContact { get; set; }
        public string CodeTypeDocument { get; set; }
        public bool? IsChecked { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Contact IdContactNavigation { get; set; }
    }
}