// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ContractType
    {
        public ContractType()
        {
            Contract = new HashSet<Contract>();
            Offer = new HashSet<Offer>();
            Recruitment = new HashSet<Recruitment>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public int? MinNoticePeriod { get; set; }
        public int? MaxNoticePeriod { get; set; }
        public string Label { get; set; }
        public bool? CalendarNoticeDays { get; set; }
        public bool? HasEndDate { get; set; }

        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
        public virtual ICollection<Recruitment> Recruitment { get; set; }
    }
}