// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Counter
    {
        public string Id { get; set; }
        public string Prefix { get; set; }
        public long? Value { get; set; }
        public int? CounterInt1 { get; set; }
        public int? CounterInt2 { get; set; }
        public int? CounterInt3 { get; set; }
        public int? CounterInt4 { get; set; }
        public int? CounterInt5 { get; set; }
        public int? CounterInt6 { get; set; }
        public int? CounterInt7 { get; set; }
        public int? CounterInt8 { get; set; }
        public int? CounterInt9 { get; set; }
        public int? CounterInt10 { get; set; }
        public bool? CounterBit1 { get; set; }
        public bool? CounterBit2 { get; set; }
        public bool? CounterBit3 { get; set; }
        public bool? CounterBit4 { get; set; }
        public bool? CounterBit5 { get; set; }
        public bool? CounterBit6 { get; set; }
        public bool? CounterBit7 { get; set; }
        public bool? CounterBit8 { get; set; }
        public bool? CounterBit9 { get; set; }
        public bool? CounterBit10 { get; set; }
        public double? CounterFloat1 { get; set; }
        public double? CounterFloat2 { get; set; }
        public double? CounterFloat3 { get; set; }
        public double? CounterFloat4 { get; set; }
        public double? CounterFloat5 { get; set; }
        public double? CounterFloat6 { get; set; }
        public double? CounterFloat7 { get; set; }
        public double? CounterFloat8 { get; set; }
        public double? CounterFloat9 { get; set; }
        public double? CounterFloat10 { get; set; }
        public string CounterVarchar1 { get; set; }
        public string CounterVarchar2 { get; set; }
        public string CounterVarchar3 { get; set; }
        public string CounterVarchar4 { get; set; }
        public string CounterVarchar5 { get; set; }
        public string CounterVarchar6 { get; set; }
        public string CounterVarchar7 { get; set; }
        public string CounterVarchar8 { get; set; }
        public string CounterVarchar9 { get; set; }
        public string CounterVarchar10 { get; set; }
        public DateTime? CounterDate1 { get; set; }
        public DateTime? CounterDate2 { get; set; }
        public DateTime? CounterDate3 { get; set; }
        public DateTime? CounterDate4 { get; set; }
        public DateTime? CounterDate5 { get; set; }
        public DateTime? CounterDate6 { get; set; }
        public DateTime? CounterDate7 { get; set; }
        public DateTime? CounterDate8 { get; set; }
        public DateTime? CounterDate9 { get; set; }
        public DateTime? CounterDate10 { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
    }
}