// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            Bank = new HashSet<Bank>();
            BankAccount = new HashSet<BankAccount>();
            Candidate = new HashSet<Candidate>();
            CashRegister = new HashSet<CashRegister>();
            City = new HashSet<City>();
            EmployeeIdCitizenshipNavigation = new HashSet<Employee>();
            EmployeeIdCountryNavigation = new HashSet<Employee>();
            Qualification = new HashSet<Qualification>();
            Tiers = new HashSet<Tiers>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Alpha2 { get; set; }
        public string Alpha3 { get; set; }
        public string NameEn { get; set; }
        public string NameFr { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Bank> Bank { get; set; }
        public virtual ICollection<BankAccount> BankAccount { get; set; }
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<CashRegister> CashRegister { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Employee> EmployeeIdCitizenshipNavigation { get; set; }
        public virtual ICollection<Employee> EmployeeIdCountryNavigation { get; set; }
        public virtual ICollection<Qualification> Qualification { get; set; }
        public virtual ICollection<Tiers> Tiers { get; set; }
    }
}