// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CriteriaMark
    {
        public int Id { get; set; }
        public double? Mark { get; set; }
        public int IdEvaluationCriteria { get; set; }
        public int IdInterviewMark { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual EvaluationCriteria IdEvaluationCriteriaNavigation { get; set; }
        public virtual InterviewMark IdInterviewMarkNavigation { get; set; }
    }
}