// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CurriculumVitae
    {
        public int Id { get; set; }
        public string Entitled { get; set; }
        public string CurriculumVitaePath { get; set; }
        public DateTime CreationDate { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdCandidate { get; set; }
        public DateTime DepositDate { get; set; }

        public virtual Candidate IdCandidateNavigation { get; set; }
    }
}