// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class CurrencyRate
    {
        public CurrencyRate()
        {
            Document = new HashSet<Document>();
        }

        public int Id { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double Coefficient { get; set; }
        public double Rate { get; set; }
        public int IdCurrency { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
}