// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Currency
    {
        public Currency()
        {
            BankAccount = new HashSet<BankAccount>();
            Company = new HashSet<Company>();
            CurrencyRate = new HashSet<CurrencyRate>();
            Document = new HashSet<Document>();
            DocumentExpenseLine = new HashSet<DocumentExpenseLine>();
            ExpenseReportDetails = new HashSet<ExpenseReportDetails>();
            FinancialCommitment = new HashSet<FinancialCommitment>();
            FundsTransfer = new HashSet<FundsTransfer>();
            Prices = new HashSet<Prices>();
            Project = new HashSet<Project>();
            Settlement = new HashSet<Settlement>();
            Tiers = new HashSet<Tiers>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Symbole { get; set; }
        public string Description { get; set; }
        public string CurrencyInLetter { get; set; }
        public string FloatInLetter { get; set; }
        public int Precision { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<BankAccount> BankAccount { get; set; }
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<CurrencyRate> CurrencyRate { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<DocumentExpenseLine> DocumentExpenseLine { get; set; }
        public virtual ICollection<ExpenseReportDetails> ExpenseReportDetails { get; set; }
        public virtual ICollection<FinancialCommitment> FinancialCommitment { get; set; }
        public virtual ICollection<FundsTransfer> FundsTransfer { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
        public virtual ICollection<Tiers> Tiers { get; set; }
    }
}