// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DateToRemember
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public DateTime? Date { get; set; }
        public int? IdTiers { get; set; }
        public int? IdContact { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Contact IdContactNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}