// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Delivery
    {
        public int Id { get; set; }
        public int IdItem { get; set; }

        public virtual Item IdItemNavigation { get; set; }
    }
}