// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Department
    {
        public Department()
        {
            Team = new HashSet<Team>();
        }

        public int Id { get; set; }
        public string DepartmentCode { get; set; }
        public string Name { get; set; }
        public DateTime CreationDate { get; set; }
        public string Domain { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Team> Team { get; set; }
    }
}