// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DetailsSettlementMode
    {
        public int Id { get; set; }
        public int? IdSettlementMode { get; set; }
        public int? IdSettlementType { get; set; }
        public int? IdPaymentMethod { get; set; }
        public double? Percentage { get; set; }
        public int? NumberDays { get; set; }
        public int? SettlementDay { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string CompletePrinting { get; set; }

        public virtual PaymentMethod IdPaymentMethodNavigation { get; set; }
        public virtual SettlementMode IdSettlementModeNavigation { get; set; }
        public virtual SettlementType IdSettlementTypeNavigation { get; set; }
    }
}