// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DetailReconciliation
    {
        public int Id { get; set; }
        public int? IdReconciliation { get; set; }
        public int? IdPayment { get; set; }
        public int? IdDetailTimetable { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual DetailTimetable IdDetailTimetableNavigation { get; set; }
        public virtual Reconciliation IdReconciliationNavigation { get; set; }
    }
}