// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DimCurrency
    {
        public int IdCurrency { get; set; }
        public string CurrencyCode { get; set; }
    }
}