// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DimItem
    {
        public int IdItem { get; set; }
        public int? IdUnitStock { get; set; }
        public int? IdUnitSales { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public int? IdItemFamily { get; set; }
        public string LabelItemFamily { get; set; }
        public int? IdSubFamily { get; set; }
        public string LabelSubFamily { get; set; }
        public int? IdItemNature { get; set; }
        public string LabelItemNature { get; set; }
    }
}