// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DimTiers
    {
        public int IdTiers { get; set; }
        public string TiersName { get; set; }
        public string TiersCode { get; set; }
        public int? IdTypeTiers { get; set; }
        public string TypeTiersLabel { get; set; }
        public string TiersAdress { get; set; }
        public int? IdCountryTiers { get; set; }
        public string CountryEn { get; set; }
        public string CountryFr { get; set; }
        public int? IdAccount { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}