// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Discussion
    {
        public Discussion()
        {
            UserDiscussionChat = new HashSet<UserDiscussionChat>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int NumberOfDiscussionMember { get; set; }
        public DateTime DateLastNotif { get; set; }

        public virtual ICollection<UserDiscussionChat> UserDiscussionChat { get; set; }
    }
}