// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentStatus
    {
        public DocumentStatus()
        {
            Document = new HashSet<Document>();
            FinancialCommitment = new HashSet<FinancialCommitment>();
            Settlement = new HashSet<Settlement>();
            StockDocument = new HashSet<StockDocument>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<FinancialCommitment> FinancialCommitment { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
        public virtual ICollection<StockDocument> StockDocument { get; set; }
    }
}