// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentRequest
    {
        public DocumentRequest()
        {
            DocumentRequestEmail = new HashSet<DocumentRequestEmail>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public DateTime SubmissionDate { get; set; }
        public DateTime DeadLine { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdDocumentRequestType { get; set; }
        public int IdEmployee { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int? TreatedBy { get; set; }
        public string Code { get; set; }

        public virtual DocumentRequestType IdDocumentRequestTypeNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Employee TreatedByNavigation { get; set; }
        public virtual ICollection<DocumentRequestEmail> DocumentRequestEmail { get; set; }
    }
}