// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentLine
    {
        public DocumentLine()
        {
            Active = new HashSet<Active>();
            Claim = new HashSet<Claim>();
            DocumentLineNegotiationOptions = new HashSet<DocumentLineNegotiationOptions>();
            DocumentLinePrices = new HashSet<DocumentLinePrices>();
            DocumentLineTaxe = new HashSet<DocumentLineTaxe>();
            InverseIdDeliveryAssociatedNavigation = new HashSet<DocumentLine>();
            InverseIdDocumentLineAssociatedNavigation = new HashSet<DocumentLine>();
            StockMovement = new HashSet<StockMovement>();
        }

        public int Id { get; set; }
        public string CodeDocumentLine { get; set; }
        public int IdDocument { get; set; }
        public int IdItem { get; set; }
        public string Designation { get; set; }
        public double MovementQty { get; set; }
        public int? IdMeasureUnit { get; set; }
        public int? IdPrices { get; set; }
        public int? IdWarehouse { get; set; }
        public double? HtUnitAmount { get; set; }
        public double? DiscountPercentage { get; set; }
        public double HtAmount { get; set; }
        public double? VatTaxAmount { get; set; }
        public double? VatTaxRate { get; set; }
        public double? HtTotalLine { get; set; }
        public double? TtcTotalLine { get; set; }
        public int? IdDocumentLineAssociated { get; set; }
        public int? IdDocumentLineStatus { get; set; }
        public bool IsDeleted { get; set; }
        public double? HtUnitAmountWithCurrency { get; set; }
        public double? HtAmountWithCurrency { get; set; }
        public double? TtcAmountWithCurrency { get; set; }
        public double? HtTotalLineWithCurrency { get; set; }
        public double? TtcTotalLineWithCurrency { get; set; }
        public double? VatTaxAmountWithCurrency { get; set; }
        public string DeletedToken { get; set; }
        public string Requirement { get; set; }
        public bool IsActive { get; set; }
        public double? ExcVatTaxAmount { get; set; }
        public double? ExcVatTaxRate { get; set; }
        public double? ExcVatTaxAmountWithCurrency { get; set; }
        public double? UnitPriceFromQuotation { get; set; }
        public double? CostPrice { get; set; }
        public double? PercentageMargin { get; set; }
        public double? SellingPrice { get; set; }
        public double? ConclusiveSellingPrice { get; set; }
        public double? TaxeAmoun { get; set; }
        public int? IdDocumentAssociated { get; set; }
        public int? IdDeliveryAssociated { get; set; }
        public int? SelectedItemSalePolicy { get; set; }
        public DateTime? DateAvailability { get; set; }
        public double? TaxeAmount { get; set; }
        public bool? IsFromGarage { get; set; }
        public int? IdStorage { get; set; }

        public virtual DocumentLine IdDeliveryAssociatedNavigation { get; set; }
        public virtual DocumentLine IdDocumentLineAssociatedNavigation { get; set; }
        public virtual Document IdDocumentNavigation { get; set; }
        public virtual Item IdItemNavigation { get; set; }
        public virtual MeasureUnit IdMeasureUnitNavigation { get; set; }
        public virtual Prices IdPricesNavigation { get; set; }
        public virtual Storage IdStorageNavigation { get; set; }
        public virtual Warehouse IdWarehouseNavigation { get; set; }
        public virtual ICollection<Active> Active { get; set; }
        public virtual ICollection<Claim> Claim { get; set; }
        public virtual ICollection<DocumentLineNegotiationOptions> DocumentLineNegotiationOptions { get; set; }
        public virtual ICollection<DocumentLinePrices> DocumentLinePrices { get; set; }
        public virtual ICollection<DocumentLineTaxe> DocumentLineTaxe { get; set; }
        public virtual ICollection<DocumentLine> InverseIdDeliveryAssociatedNavigation { get; set; }
        public virtual ICollection<DocumentLine> InverseIdDocumentLineAssociatedNavigation { get; set; }
        public virtual ICollection<StockMovement> StockMovement { get; set; }
    }
}