// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentExpenseLine
    {
        public int Id { get; set; }
        public string CodeExpenseLine { get; set; }
        public int IdDocument { get; set; }
        public int IdExpense { get; set; }
        public string Designation { get; set; }
        public int? IdTaxe { get; set; }
        public double HtAmoutLine { get; set; }
        public double TtcAmoutLine { get; set; }
        public double HtAmountLineWithCurrency { get; set; }
        public double TtcAmountLineWithCurrency { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdCurrency { get; set; }
        public double? ExchangeRate { get; set; }
        public int? IdTiers { get; set; }
        public double? TaxeAmoun { get; set; }
        public double HtAmountLineWithCurrencyPercentage { get; set; }
        public double? TaxeAmount { get; set; }

        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual Document IdDocumentNavigation { get; set; }
        public virtual Expense IdExpenseNavigation { get; set; }
        public virtual Taxe IdTaxeNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}