// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentWithholdingTax
    {
        public DocumentWithholdingTax()
        {
            SettlementDocumentWithholdingTax = new HashSet<SettlementDocumentWithholdingTax>();
        }

        public int Id { get; set; }
        public int IdDocument { get; set; }
        public int IdWithholdingTax { get; set; }
        public double AmountWithCurrency { get; set; }
        public double Amount { get; set; }
        public double WithholdingTaxWithCurrency { get; set; }
        public double WithholdingTax { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double? RemainingWithholdingTaxWithCurrency { get; set; }
        public double? RemainingWithholdingTax { get; set; }

        public virtual Document IdDocumentNavigation { get; set; }
        public virtual WithholdingTax IdWithholdingTaxNavigation { get; set; }
        public virtual ICollection<SettlementDocumentWithholdingTax> SettlementDocumentWithholdingTax { get; set; }
    }
}