// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentTypeRelation
    {
        public int Id { get; set; }
        public string CodeDocumentType { get; set; }
        public string CodeDocumentTypeAssociated { get; set; }

        public virtual DocumentType CodeDocumentTypeAssociatedNavigation { get; set; }
        public virtual DocumentType CodeDocumentTypeNavigation { get; set; }
    }
}