// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentLineTaxe
    {
        public int Id { get; set; }
        public int IdTaxe { get; set; }
        public int IdDocumentLine { get; set; }
        public double? TaxeValue { get; set; }
        public double? TaxeAmount { get; set; }
        public int TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public double? TaxeBase { get; set; }
        public double? TaxeBaseWithCurrency { get; set; }
        public double? TaxeValueWithCurrency { get; set; }

        public virtual DocumentLine IdDocumentLineNavigation { get; set; }
        public virtual Taxe IdTaxeNavigation { get; set; }
    }
}