// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class DocumentLineNegotiationOptions
    {
        public int Id { get; set; }
        public int IdDocumentLine { get; set; }
        public double? Price { get; set; }
        public double? Qty { get; set; }
        public bool IsFinal { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsRejected { get; set; }
        public DateTime CreationDate { get; set; }
        public int IdUser { get; set; }
        public double? QteSupplier { get; set; }
        public double? PriceSupplier { get; set; }
        public int IdItem { get; set; }

        public virtual DocumentLine IdDocumentLineNavigation { get; set; }
        public virtual Item IdItemNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
    }
}