// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistence.Entities
{
    public partial class Document
    {
        public Document()
        {
            ClaimIdDeliveryDocumentNavigation = new HashSet<Claim>();
            ClaimIdDocumentNavigation = new HashSet<Claim>();
            ClaimIdMovementInNavigation = new HashSet<Claim>();
            ClaimIdMovementOutNavigation = new HashSet<Claim>();
            ClaimIdPurchaseAssetDocumentNavigation = new HashSet<Claim>();
            ClaimIdPurchaseDocumentNavigation = new HashSet<Claim>();
            ClaimIdReceiptDocumentNavigation = new HashSet<Claim>();
            ClaimIdSalesAssetDocumentNavigation = new HashSet<Claim>();
            ClaimIdSalesDocumentNavigation = new HashSet<Claim>();
            DocumentExpenseLine = new HashSet<DocumentExpenseLine>();
            DocumentLine = new HashSet<DocumentLine>();
            DocumentTaxsResume = new HashSet<DocumentTaxsResume>();
            DocumentWithholdingTax = new HashSet<DocumentWithholdingTax>();
            FinancialCommitment = new HashSet<FinancialCommitment>();
            TicketIdDeliveryFormNavigation = new HashSet<Ticket>();
            TicketIdInvoiceNavigation = new HashSet<Ticket>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Reference { get; set; }
        public int IdDocumentStatus { get; set; }
        public string DocumentTypeCode { get; set; }
        public string Informations { get; set; }
        public int? IdTiers { get; set; }
        public int? IdContact { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? ValidationDate { get; set; }
        public DateTime DocumentDate { get; set; }
        public DateTime? DateTerm { get; set; }
        public double? DocumentHtprice { get; set; }
        public double? DocumentTotalVatTaxes { get; set; }
        public double? DocumentTtcprice { get; set; }
        public double? DocumentRemainingAmount { get; set; }
        public double? DocumentAmountPaid { get; set; }
        public double? DocumentTotalDiscount { get; set; }
        public string AmountInLetter { get; set; }
        public bool? WithHoldingFlag { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdDiscountGroupTiers { get; set; }
        public int? IdPaymentMethod { get; set; }
        public int? IdTaxeGroupTiers { get; set; }
        public string DocumentVarchar2 { get; set; }
        public string DocumentVarchar3 { get; set; }
        public string DocumentVarchar7 { get; set; }
        public string DocumentVarchar8 { get; set; }
        public string Name { get; set; }
        public string MatriculeFiscale { get; set; }
        public int? IdUsedCurrency { get; set; }
        public double? ExchangeRate { get; set; }
        public double? DocumentHtpriceWithCurrency { get; set; }
        public double? DocumentTotalVatTaxesWithCurrency { get; set; }
        public double? DocumentTtcpriceWithCurrency { get; set; }
        public double? DocumentRemainingAmountWithCurrency { get; set; }
        public double? DocumentAmountPaidWithCurrency { get; set; }
        public double? DocumentTotalDiscountWithCurrency { get; set; }
        public string Adress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public int? IdSettlementMode { get; set; }
        public string AttachmentUrl { get; set; }
        public string DeletedToken { get; set; }
        public int? IdBankAccount { get; set; }
        public double? DocumentPriceIncludeVat { get; set; }
        public double? DocumentPriceIncludeVatwithCurrency { get; set; }
        public double? DocumentOtherTaxes { get; set; }
        public double? DocumentOtherTaxesWithCurrency { get; set; }
        public int? DocumentMonthDate { get; set; }
        public int? IdDecisionMaker { get; set; }
        public double? DocumentTotalExcVatTaxes { get; set; }
        public double? DocumentTotalExcVatTaxesWithCurrency { get; set; }
        public int? IdValidator { get; set; }
        public int? IdDocumentAssociated { get; set; }
        public bool IsTermBilling { get; set; }
        public int? IdPriceRequest { get; set; }
        public bool IsGenerated { get; set; }
        public int? IdTimeSheet { get; set; }
        public int? IdProject { get; set; }
        public bool IsAccounted { get; set; }
        public bool? IsBtoB { get; set; }
        public int? IdProvision { get; set; }
        public int? IdExchangeRate { get; set; }
        public int? IdCreator { get; set; }
        public int? InoicingType { get; set; }
        public int? IdDeliveryType { get; set; }
        public string DocumentInvoicingNumber { get; set; }
        public DateTime? DocumentInvoicingDate { get; set; }
        public bool? IsDeliverySuccess { get; set; }
        public double? Coefficient { get; set; }
        public int? IdInvoiceEcommerce { get; set; }
        public string ProvisionalCode { get; set; }
        public bool IsRestaurn { get; set; }
        public int? Priority { get; set; }
        public bool? IsFromGarage { get; set; }
        public bool? IsForPos { get; set; }
        public int? IdVehicle { get; set; }
        public bool IsSynchronizedBtoB { get; set; }
        public int? IdSessionCounterSales { get; set; }
        public int? IdSalesDepositInvoice { get; set; }
        public int? IdSalesOrder { get; set; }
        public int? IdCreatorBtob { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual Contact IdContactNavigation { get; set; }
        public virtual User IdCreatorNavigation { get; set; }
        public virtual DeliveryType IdDeliveryTypeNavigation { get; set; }
        public virtual DocumentStatus IdDocumentStatusNavigation { get; set; }
        public virtual CurrencyRate IdExchangeRateNavigation { get; set; }
        public virtual PaymentMethod IdPaymentMethodNavigation { get; set; }
        public virtual PriceRequest IdPriceRequestNavigation { get; set; }
        public virtual Provisioning IdProvisionNavigation { get; set; }
        public virtual SessionCash IdSessionCounterSalesNavigation { get; set; }
        public virtual SettlementMode IdSettlementModeNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual Currency IdUsedCurrencyNavigation { get; set; }
        public virtual User IdValidatorNavigation { get; set; }
        public virtual Vehicle IdVehicleNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdDeliveryDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdMovementInNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdMovementOutNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdPurchaseAssetDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdPurchaseDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdReceiptDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdSalesAssetDocumentNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdSalesDocumentNavigation { get; set; }
        public virtual ICollection<DocumentExpenseLine> DocumentExpenseLine { get; set; }
        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<DocumentTaxsResume> DocumentTaxsResume { get; set; }
        public virtual ICollection<DocumentWithholdingTax> DocumentWithholdingTax { get; set; }
        public virtual ICollection<FinancialCommitment> FinancialCommitment { get; set; }
        public virtual ICollection<Ticket> TicketIdDeliveryFormNavigation { get; set; }
        public virtual ICollection<Ticket> TicketIdInvoiceNavigation { get; set; }
    }
}