// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Email
    {
        public Email()
        {
            Candidacy = new HashSet<Candidacy>();
            DocumentRequestEmail = new HashSet<DocumentRequestEmail>();
            ExpenseReportEmail = new HashSet<ExpenseReportEmail>();
            Interview = new HashSet<Interview>();
            InterviewEmail = new HashSet<InterviewEmail>();
            LeaveEmail = new HashSet<LeaveEmail>();
            NewUserEmail = new HashSet<NewUserEmail>();
            Offer = new HashSet<Offer>();
        }

        public int Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int Status { get; set; }
        public string Sender { get; set; }
        public string Receivers { get; set; }
        public int AttemptsToSendNumber { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Candidacy> Candidacy { get; set; }
        public virtual ICollection<DocumentRequestEmail> DocumentRequestEmail { get; set; }
        public virtual ICollection<ExpenseReportEmail> ExpenseReportEmail { get; set; }
        public virtual ICollection<Interview> Interview { get; set; }
        public virtual ICollection<InterviewEmail> InterviewEmail { get; set; }
        public virtual ICollection<LeaveEmail> LeaveEmail { get; set; }
        public virtual ICollection<NewUserEmail> NewUserEmail { get; set; }
        public virtual ICollection<Offer> Offer { get; set; }
    }
}