// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Employee
    {
        public Employee()
        {
            BillingEmployee = new HashSet<BillingEmployee>();
            Candidate = new HashSet<Candidate>();
            CnssDeclarationDetails = new HashSet<CnssDeclarationDetails>();
            Contract = new HashSet<Contract>();
            DocumentRequestIdEmployeeNavigation = new HashSet<DocumentRequest>();
            DocumentRequestTreatedByNavigation = new HashSet<DocumentRequest>();
            EmployeeDocument = new HashSet<EmployeeDocument>();
            EmployeeProject = new HashSet<EmployeeProject>();
            EmployeeSkills = new HashSet<EmployeeSkills>();
            EmployeeTeam = new HashSet<EmployeeTeam>();
            EmployeeTrainingSession = new HashSet<EmployeeTrainingSession>();
            ExitEmailForEmployee = new HashSet<ExitEmailForEmployee>();
            ExitEmployee = new HashSet<ExitEmployee>();
            ExpenseReportIdEmployeeNavigation = new HashSet<ExpenseReport>();
            ExpenseReportTreatedByNavigation = new HashSet<ExpenseReport>();
            FileDriveSharedDocument = new HashSet<FileDriveSharedDocument>();
            History = new HashSet<History>();
            InterviewIdCreatorNavigation = new HashSet<Interview>();
            InterviewIdSupervisorNavigation = new HashSet<Interview>();
            InterviewMark = new HashSet<InterviewMark>();
            InverseIdUpperHierarchyNavigation = new HashSet<Employee>();
            Item = new HashSet<Item>();
            JobEmployee = new HashSet<JobEmployee>();
            LeaveBalanceRemaining = new HashSet<LeaveBalanceRemaining>();
            LeaveIdEmployeeNavigation = new HashSet<Leave>();
            LeaveTreatedByNavigation = new HashSet<Leave>();
            Loan = new HashSet<Loan>();
            MobilityRequest = new HashSet<MobilityRequest>();
            Note = new HashSet<Note>();
            Objective = new HashSet<Objective>();
            ParentInCharge = new HashSet<ParentInCharge>();
            Payslip = new HashSet<Payslip>();
            Qualification = new HashSet<Qualification>();
            RecruitmentIdEmployeeAuthorNavigation = new HashSet<Recruitment>();
            RecruitmentIdEmployeeValidatorNavigation = new HashSet<Recruitment>();
            ReviewFormation = new HashSet<ReviewFormation>();
            ReviewIdEmployeeCollaboratorNavigation = new HashSet<Review>();
            ReviewIdManagerNavigation = new HashSet<Review>();
            ReviewSkills = new HashSet<ReviewSkills>();
            SharedDocument = new HashSet<SharedDocument>();
            SourceDeduction = new HashSet<SourceDeduction>();
            SourceDeductionSessionEmployee = new HashSet<SourceDeductionSessionEmployee>();
            Team = new HashSet<Team>();
            TimeSheetIdEmployeeNavigation = new HashSet<TimeSheet>();
            TimeSheetIdEmployeeTreatedNavigation = new HashSet<TimeSheet>();
            TrainingByEmployee = new HashSet<TrainingByEmployee>();
            TrainingRequestIdEmployeeAuthorNavigation = new HashSet<TrainingRequest>();
            TrainingRequestIdEmployeeCollaboratorNavigation = new HashSet<TrainingRequest>();
            TrainingSession = new HashSet<TrainingSession>();
            TransferOrderDetails = new HashSet<TransferOrderDetails>();
            User = new HashSet<User>();
            Warehouse = new HashSet<Warehouse>();
        }

        public int Id { get; set; }
        public int Sex { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Matricule { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public int? IdCountry { get; set; }
        public int? IdCity { get; set; }
        public string ZipCode { get; set; }
        public string PersonalPhone { get; set; }
        public string ProfessionalPhone { get; set; }
        public DateTime? BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string PseudoSkype { get; set; }
        public string Facebook { get; set; }
        public string Linkedin { get; set; }
        public string SocialSecurityNumber { get; set; }
        public int? ChildrenNumber { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdGrade { get; set; }
        public int? IdUpperHierarchy { get; set; }
        public string WorkingLicenseNumber { get; set; }
        public DateTime HiringDate { get; set; }
        public string Category { get; set; }
        public string Cin { get; set; }
        public bool? FamilyLeader { get; set; }
        public int? Echelon { get; set; }
        public string CinAttached { get; set; }
        public double? HomeLoan { get; set; }
        public int? ChildrenNoScholar { get; set; }
        public int? ChildrenDisabled { get; set; }
        public bool IsForeign { get; set; }
        public int? DependentParent { get; set; }
        public string Picture { get; set; }
        public string Rib { get; set; }
        public DateTime? ResignationDate { get; set; }
        public DateTime? ResignationDepositDate { get; set; }
        public int? IdCitizenship { get; set; }
        public int? IdPaymentType { get; set; }
        public string SharedDocumentsPassword { get; set; }
        public string PersonalEmail { get; set; }
        public int? IdOffice { get; set; }
        public string HierarchyLevel { get; set; }
        public int? MaritalStatus { get; set; }
        public int? IdBank { get; set; }
        public int Status { get; set; }
        public bool ResignedFromExitEmployee { get; set; }
        public string FullName { get; set; }

        public virtual Bank IdBankNavigation { get; set; }
        public virtual Country IdCitizenshipNavigation { get; set; }
        public virtual City IdCityNavigation { get; set; }
        public virtual Country IdCountryNavigation { get; set; }
        public virtual Grade IdGradeNavigation { get; set; }
        public virtual Office IdOfficeNavigation { get; set; }
        public virtual PaymentType IdPaymentTypeNavigation { get; set; }
        public virtual Employee IdUpperHierarchyNavigation { get; set; }
        public virtual ICollection<BillingEmployee> BillingEmployee { get; set; }
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<CnssDeclarationDetails> CnssDeclarationDetails { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<DocumentRequest> DocumentRequestIdEmployeeNavigation { get; set; }
        public virtual ICollection<DocumentRequest> DocumentRequestTreatedByNavigation { get; set; }
        public virtual ICollection<EmployeeDocument> EmployeeDocument { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProject { get; set; }
        public virtual ICollection<EmployeeSkills> EmployeeSkills { get; set; }
        public virtual ICollection<EmployeeTeam> EmployeeTeam { get; set; }
        public virtual ICollection<EmployeeTrainingSession> EmployeeTrainingSession { get; set; }
        public virtual ICollection<ExitEmailForEmployee> ExitEmailForEmployee { get; set; }
        public virtual ICollection<ExitEmployee> ExitEmployee { get; set; }
        public virtual ICollection<ExpenseReport> ExpenseReportIdEmployeeNavigation { get; set; }
        public virtual ICollection<ExpenseReport> ExpenseReportTreatedByNavigation { get; set; }
        public virtual ICollection<FileDriveSharedDocument> FileDriveSharedDocument { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<Interview> InterviewIdCreatorNavigation { get; set; }
        public virtual ICollection<Interview> InterviewIdSupervisorNavigation { get; set; }
        public virtual ICollection<InterviewMark> InterviewMark { get; set; }
        public virtual ICollection<Employee> InverseIdUpperHierarchyNavigation { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<JobEmployee> JobEmployee { get; set; }
        public virtual ICollection<LeaveBalanceRemaining> LeaveBalanceRemaining { get; set; }
        public virtual ICollection<Leave> LeaveIdEmployeeNavigation { get; set; }
        public virtual ICollection<Leave> LeaveTreatedByNavigation { get; set; }
        public virtual ICollection<Loan> Loan { get; set; }
        public virtual ICollection<MobilityRequest> MobilityRequest { get; set; }
        public virtual ICollection<Note> Note { get; set; }
        public virtual ICollection<Objective> Objective { get; set; }
        public virtual ICollection<ParentInCharge> ParentInCharge { get; set; }
        public virtual ICollection<Payslip> Payslip { get; set; }
        public virtual ICollection<Qualification> Qualification { get; set; }
        public virtual ICollection<Recruitment> RecruitmentIdEmployeeAuthorNavigation { get; set; }
        public virtual ICollection<Recruitment> RecruitmentIdEmployeeValidatorNavigation { get; set; }
        public virtual ICollection<ReviewFormation> ReviewFormation { get; set; }
        public virtual ICollection<Review> ReviewIdEmployeeCollaboratorNavigation { get; set; }
        public virtual ICollection<Review> ReviewIdManagerNavigation { get; set; }
        public virtual ICollection<ReviewSkills> ReviewSkills { get; set; }
        public virtual ICollection<SharedDocument> SharedDocument { get; set; }
        public virtual ICollection<SourceDeduction> SourceDeduction { get; set; }
        public virtual ICollection<SourceDeductionSessionEmployee> SourceDeductionSessionEmployee { get; set; }
        public virtual ICollection<Team> Team { get; set; }
        public virtual ICollection<TimeSheet> TimeSheetIdEmployeeNavigation { get; set; }
        public virtual ICollection<TimeSheet> TimeSheetIdEmployeeTreatedNavigation { get; set; }
        public virtual ICollection<TrainingByEmployee> TrainingByEmployee { get; set; }
        public virtual ICollection<TrainingRequest> TrainingRequestIdEmployeeAuthorNavigation { get; set; }
        public virtual ICollection<TrainingRequest> TrainingRequestIdEmployeeCollaboratorNavigation { get; set; }
        public virtual ICollection<TrainingSession> TrainingSession { get; set; }
        public virtual ICollection<TransferOrderDetails> TransferOrderDetails { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}