// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class EmployeeTeam
    {
        public int Id { get; set; }
        public DateTime AssignmentDate { get; set; }
        public DateTime? UnassignmentDate { get; set; }
        public int IdEmployee { get; set; }
        public int IdTeam { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public bool IsAssigned { get; set; }
        public double AssignmentPercentage { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Team IdTeamNavigation { get; set; }
    }
}