// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class EmployeeDocument
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public int Type { get; set; }
        public string Value { get; set; }
        public int IdEmployee { get; set; }
        public string AttachedFile { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public bool IsPermanent { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
    }
}