// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class EmployeeProject
    {
        public int Id { get; set; }
        public DateTime AssignmentDate { get; set; }
        public DateTime? UnassignmentDate { get; set; }
        public int IdEmployee { get; set; }
        public int IdProject { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double? AverageDailyRate { get; set; }
        public bool IsBillable { get; set; }
        public double? AssignmentPercentage { get; set; }
        public string CompanyCode { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Project IdProjectNavigation { get; set; }
    }
}