// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class EntityAxisValues
    {
        public int Id { get; set; }
        public int? IdAxisValue { get; set; }
        public int? IdEntityItem { get; set; }
        public int? Entity { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Entity EntityNavigation { get; set; }
        public virtual AxisValue IdAxisValueNavigation { get; set; }
    }
}