// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// Table which contains all the entities existing in the database of the ERP
    /// </summary>
    public partial class Entity
    {
        public Entity()
        {
            AxisEntity = new HashSet<AxisEntity>();
            Comment = new HashSet<Comment>();
            EntityAxisValues = new HashSet<EntityAxisValues>();
            EntityCodification = new HashSet<EntityCodification>();
            InverseIdRelatedEntityNavigation = new HashSet<Entity>();
            ReportTemplate = new HashSet<ReportTemplate>();
        }

        /// <summary>
        /// Unique identifier of the table entity
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Plan of database where entitées allocated to him
        /// </summary>
        public string TableSchema { get; set; }
        /// <summary>
        /// Name of entity (In the database)
        /// </summary>
        public string EntityName { get; set; }
        /// <summary>
        /// The user can change the names of the static tables in this column, just to differentiate the entities
        /// </summary>
        public string TableName { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Fr { get; set; }
        public string Ar { get; set; }
        public string En { get; set; }
        public string De { get; set; }
        public string Ch { get; set; }
        public string Es { get; set; }
        public bool? IsReference { get; set; }
        public int? IdRelatedEntity { get; set; }
        public string DeletedToken { get; set; }

        public virtual Entity IdRelatedEntityNavigation { get; set; }
        public virtual ICollection<AxisEntity> AxisEntity { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<EntityAxisValues> EntityAxisValues { get; set; }
        public virtual ICollection<EntityCodification> EntityCodification { get; set; }
        public virtual ICollection<Entity> InverseIdRelatedEntityNavigation { get; set; }
        public virtual ICollection<ReportTemplate> ReportTemplate { get; set; }
    }
}