// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class EntityCodification
    {
        public int Id { get; set; }
        public int? IdEntity { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
        public int? IdCodification { get; set; }

        public virtual Codification IdCodificationNavigation { get; set; }
        public virtual Entity IdEntityNavigation { get; set; }
    }
}