// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExitEmployee
    {
        public ExitEmployee()
        {
            ExitActionEmployee = new HashSet<ExitActionEmployee>();
            ExitEmailForEmployee = new HashSet<ExitEmailForEmployee>();
            ExitEmployeeLeaveLine = new HashSet<ExitEmployeeLeaveLine>();
            ExitEmployeePayLine = new HashSet<ExitEmployeePayLine>();
            Interview = new HashSet<Interview>();
        }

        public int Id { get; set; }
        public int IdExitReason { get; set; }
        public int IdEmployee { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string ExitEmployeeAttachementFile { get; set; }
        public string CommentRh { get; set; }
        public int? Status { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int? TreatedBy { get; set; }
        public DateTime? LegalExitDate { get; set; }
        public bool? DamagingDeparture { get; set; }
        public DateTime? ExitDepositDate { get; set; }
        public DateTime? MinNoticePeriodDate { get; set; }
        public DateTime? MaxNoticePeriodDate { get; set; }
        public DateTime? ExitPhysicalDate { get; set; }
        public int? StatePay { get; set; }
        public int? StateLeave { get; set; }
        public DateTime CreationDate { get; set; }
        public bool RecoveredMaterial { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual ExitReason IdExitReasonNavigation { get; set; }
        public virtual ICollection<ExitActionEmployee> ExitActionEmployee { get; set; }
        public virtual ICollection<ExitEmailForEmployee> ExitEmailForEmployee { get; set; }
        public virtual ICollection<ExitEmployeeLeaveLine> ExitEmployeeLeaveLine { get; set; }
        public virtual ICollection<ExitEmployeePayLine> ExitEmployeePayLine { get; set; }
        public virtual ICollection<Interview> Interview { get; set; }
    }
}