// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExitActionEmployee
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdExitEmployee { get; set; }
        public int? IdExitAction { get; set; }
        public bool VerifyAction { get; set; }

        public virtual ExitAction IdExitActionNavigation { get; set; }
        public virtual ExitEmployee IdExitEmployeeNavigation { get; set; }
    }
}