// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExitEmployeePayLine
    {
        public ExitEmployeePayLine()
        {
            ExitEmployeePayLineSalaryRule = new HashSet<ExitEmployeePayLineSalaryRule>();
        }

        public int Id { get; set; }
        public string Details { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double? NumberDayWorked { get; set; }
        public int? State { get; set; }
        public DateTime Month { get; set; }
        public int IdExitEmployee { get; set; }

        public virtual ExitEmployee IdExitEmployeeNavigation { get; set; }
        public virtual ICollection<ExitEmployeePayLineSalaryRule> ExitEmployeePayLineSalaryRule { get; set; }
    }
}