// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExitEmployeeLeaveLine
    {
        public int Id { get; set; }
        public string Details { get; set; }
        public DateTime Month { get; set; }
        public string DayTakenPerMonth { get; set; }
        public double TotalTakenPerMonth { get; set; }
        public int AcquiredParMonth { get; set; }
        public int? IdLeaveType { get; set; }
        public double CumulativeTaken { get; set; }
        public double CumulativeAcquired { get; set; }
        public double BalancePerMonth { get; set; }
        public int? IdExitEmployee { get; set; }
        public double TotalTakenPerYear { get; set; }
        public double AcquiredPerYear { get; set; }
        public int Year { get; set; }
        public double BalancePerYear { get; set; }
        public string DayTakenPerYear { get; set; }

        public virtual ExitEmployee IdExitEmployeeNavigation { get; set; }
        public virtual LeaveType IdLeaveTypeNavigation { get; set; }
    }
}