// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExitEmployeePayLineSalaryRule
    {
        public int Id { get; set; }
        public int? IdSalaryRule { get; set; }
        public int? IdExitEmployeePayLine { get; set; }
        public double? Value { get; set; }

        public virtual ExitEmployeePayLine IdExitEmployeePayLineNavigation { get; set; }
        public virtual SalaryRule IdSalaryRuleNavigation { get; set; }
    }
}