// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Expense
    {
        public Expense()
        {
            DocumentExpenseLine = new HashSet<DocumentExpenseLine>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int IdItem { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdTaxe { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual Taxe IdTaxeNavigation { get; set; }
        public virtual ICollection<DocumentExpenseLine> DocumentExpenseLine { get; set; }
    }
}