// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExpenseReport
    {
        public ExpenseReport()
        {
            ExpenseReportDetails = new HashSet<ExpenseReportDetails>();
            ExpenseReportEmail = new HashSet<ExpenseReportEmail>();
        }

        public int Id { get; set; }
        public string Purpose { get; set; }
        public DateTime SubmissionDate { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int Status { get; set; }
        public int IdEmployee { get; set; }
        public double TotalAmount { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? TreatedBy { get; set; }
        public string Code { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Employee TreatedByNavigation { get; set; }
        public virtual ICollection<ExpenseReportDetails> ExpenseReportDetails { get; set; }
        public virtual ICollection<ExpenseReportEmail> ExpenseReportEmail { get; set; }
    }
}