// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExpenseReportDetails
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public double Amount { get; set; }
        public int IdCurrency { get; set; }
        public int IdExpenseReport { get; set; }
        public int IdExpenseReportDetailsType { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public DateTime Date { get; set; }
        public string AttachmentUrl { get; set; }

        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual ExpenseReportDetailsType IdExpenseReportDetailsTypeNavigation { get; set; }
        public virtual ExpenseReport IdExpenseReportNavigation { get; set; }
    }
}