// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExternalTrainerSkills
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdExternalTrainer { get; set; }
        public int? IdSkills { get; set; }
        public bool? IsRecognized { get; set; }
        public bool? IsCertified { get; set; }
        public int? Rate { get; set; }

        public virtual ExternalTrainer IdExternalTrainerNavigation { get; set; }
        public virtual Skills IdSkillsNavigation { get; set; }
    }
}