// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExternalTrainer
    {
        public ExternalTrainer()
        {
            ExternalTrainerSkills = new HashSet<ExternalTrainerSkills>();
            ExternalTraining = new HashSet<ExternalTraining>();
            TrainingSession = new HashSet<TrainingSession>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int? YearsOfExperience { get; set; }
        public double? HourCost { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<ExternalTrainerSkills> ExternalTrainerSkills { get; set; }
        public virtual ICollection<ExternalTraining> ExternalTraining { get; set; }
        public virtual ICollection<TrainingSession> TrainingSession { get; set; }
    }
}