// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ExternalTraining
    {
        public int Id { get; set; }
        public int IdExternalTrainer { get; set; }
        public int IdTrainingCenterRoom { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdTrainingSession { get; set; }

        public virtual ExternalTrainer IdExternalTrainerNavigation { get; set; }
        public virtual TrainingCenterRoom IdTrainingCenterRoomNavigation { get; set; }
        public virtual TrainingSession IdTrainingSessionNavigation { get; set; }
    }
}