// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Family
    {
        public Family()
        {
            Item = new HashSet<Item>();
            SubFamily = new HashSet<SubFamily>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public string UrlPicture { get; set; }
        public int? IdCategoryEcommerce { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<SubFamily> SubFamily { get; set; }
    }
}