// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class FileDrive
    {
        public FileDrive()
        {
            InverseIdParentNavigation = new HashSet<FileDrive>();
            UserFileAccess = new HashSet<UserFileAccess>();
            UserFileModification = new HashSet<UserFileModification>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public string Type { get; set; }
        public int? IdParent { get; set; }
        public int Size { get; set; }
        public string Path { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual FileDrive IdParentNavigation { get; set; }
        public virtual ICollection<FileDrive> InverseIdParentNavigation { get; set; }
        public virtual ICollection<UserFileAccess> UserFileAccess { get; set; }
        public virtual ICollection<UserFileModification> UserFileModification { get; set; }
    }
}