// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class FinancialCommitment
    {
        public FinancialCommitment()
        {
            SettlementCommitment = new HashSet<SettlementCommitment>();
        }

        public int Id { get; set; }
        public int? IdDocument { get; set; }
        public DateTime CommitmentDate { get; set; }
        public double RemainingAmount { get; set; }
        public double? RemainingAmountWithCurrency { get; set; }
        public int? IdPaymentMethod { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdStatus { get; set; }
        public double? Amount { get; set; }
        public double? AmountWithCurrency { get; set; }
        public int? BenefitPeriod { get; set; }
        public int Direction { get; set; }
        public string Code { get; set; }
        public int? IdTiers { get; set; }
        public int? IdCurrency { get; set; }
        public double? ExchangeRate { get; set; }
        public DateTime? FinancialCommitmentDate { get; set; }
        public double? WithholdingTaxWithCurrency { get; set; }
        public double? WithholdingTax { get; set; }
        public double? RemainingWithholdingTax { get; set; }
        public double? RemainingWithholdingTaxWithCurrency { get; set; }
        public double? AmountWithoutWithholdingTax { get; set; }
        public double? AmountWithoutWithholdingTaxWithCurrency { get; set; }
        public double? TtcWithholdingTaxWithCurrency { get; set; }
        public double? TtcWithholdingTax { get; set; }
        public double? VatWithholdingTaxWithCurrency { get; set; }
        public double? VatWithholdingTax { get; set; }
        public double? RemainingVatWithholdingTaxWithCurrency { get; set; }
        public double? RemainingVatWithholdingTax { get; set; }

        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual Document IdDocumentNavigation { get; set; }
        public virtual PaymentMethod IdPaymentMethodNavigation { get; set; }
        public virtual DocumentStatus IdStatusNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual ICollection<SettlementCommitment> SettlementCommitment { get; set; }
    }
}