// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// This table contains all the features existing in our ERP (Ajouter_Article, Edit_Article, List_Article, Confirm_Article....)
    /// </summary>
    public partial class Functionality
    {
        public Functionality()
        {
            Information = new HashSet<Information>();
        }

        /// <summary>
        /// Unique identifier of Functionaity table
        /// </summary>
        public Guid IdFunctionality { get; set; }
        /// <summary>
        /// Name of Functionality 
        /// </summary>
        public string FunctionalityName { get; set; }
        /// <summary>
        /// Foreign key on the table RequestType (Contains every type of the features)
        /// </summary>
        public int? IdRequestType { get; set; }
        /// <summary>
        /// Description of the name modulates in Drench language 
        /// </summary>
        public string Fr { get; set; }
        /// <summary>
        /// Description of the name modulates in English language 
        /// </summary>
        public string En { get; set; }
        /// <summary>
        /// Description of the name modulates in Arabic language 
        /// </summary>
        public string Ar { get; set; }
        /// <summary>
        /// Description of the name modulates in Deutsche language 
        /// </summary>
        public string De { get; set; }
        /// <summary>
        /// Description of the name modulates in Chine language 
        /// </summary>
        public string Ch { get; set; }
        /// <summary>
        /// Description of the name modulates in Spanich language 
        /// </summary>
        public string Es { get; set; }
        public string DefaultRoute { get; set; }
        public bool? IsDefaultRoute { get; set; }
        public string ApiRole { get; set; }

        public virtual RequestType IdRequestTypeNavigation { get; set; }
        public virtual ICollection<Information> Information { get; set; }
    }
}