// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class FundsTransfer
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int Type { get; set; }
        public int IdSourceCash { get; set; }
        public int IdDestinationCash { get; set; }
        public int Status { get; set; }
        public double Amount { get; set; }
        public double AmountWithCurrency { get; set; }
        public int IdCurrency { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdCashier { get; set; }
        public DateTime TransferDate { get; set; }

        public virtual User IdCashierNavigation { get; set; }
        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual CashRegister IdDestinationCashNavigation { get; set; }
        public virtual CashRegister IdSourceCashNavigation { get; set; }
    }
}