// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Information
    {
        public Information()
        {
            InverseIdInfoParentNavigation = new HashSet<Information>();
            Message = new HashSet<Message>();
            UserInfo = new HashSet<UserInfo>();
        }

        public int IdInfo { get; set; }
        public Guid IdFunctionality { get; set; }
        public string Url { get; set; }
        public string Fr { get; set; }
        public string En { get; set; }
        public string Ar { get; set; }
        public string De { get; set; }
        public string Ch { get; set; }
        public string Es { get; set; }
        public bool? IsMail { get; set; }
        public bool? IsNotification { get; set; }
        public string MailSubject { get; set; }
        public bool? IsAcceptedInfo { get; set; }
        public bool? IsToManager { get; set; }
        public int? IdInfoParent { get; set; }
        public string TranslationKey { get; set; }
        public string Type { get; set; }

        public virtual Functionality IdFunctionalityNavigation { get; set; }
        public virtual Information IdInfoParentNavigation { get; set; }
        public virtual ICollection<Information> InverseIdInfoParentNavigation { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
    }
}