// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class InterviewQuestion
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Question { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdTheme { get; set; }

        public virtual InterviewQuestionTheme IdThemeNavigation { get; set; }
    }
}