// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Interview
    {
        public Interview()
        {
            InterviewEmail = new HashSet<InterviewEmail>();
            InterviewMark = new HashSet<InterviewMark>();
            Question = new HashSet<Question>();
        }

        public int Id { get; set; }
        public double? AverageMark { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime InterviewDate { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
        public int? IdInterviewType { get; set; }
        public int? IdCandidacy { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdEmail { get; set; }
        public int? IdReview { get; set; }
        public int? IdSupervisor { get; set; }
        public int? IdCreator { get; set; }
        public string Token { get; set; }
        public TimeSpan EndTime { get; set; }
        public int? IdExitEmployee { get; set; }

        public virtual Candidacy IdCandidacyNavigation { get; set; }
        public virtual Employee IdCreatorNavigation { get; set; }
        public virtual Email IdEmailNavigation { get; set; }
        public virtual ExitEmployee IdExitEmployeeNavigation { get; set; }
        public virtual InterviewType IdInterviewTypeNavigation { get; set; }
        public virtual Review IdReviewNavigation { get; set; }
        public virtual Employee IdSupervisorNavigation { get; set; }
        public virtual ICollection<InterviewEmail> InterviewEmail { get; set; }
        public virtual ICollection<InterviewMark> InterviewMark { get; set; }
        public virtual ICollection<Question> Question { get; set; }
    }
}