// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ItemSalesPrice
    {
        public int Id { get; set; }
        public int IdItem { get; set; }
        public int IdSalesPrice { get; set; }
        public double Percentage { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual SalesPrice IdSalesPriceNavigation { get; set; }
    }
}