// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ItemTiers
    {
        public int Id { get; set; }
        public int IdItem { get; set; }
        public int IdTiers { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public double? PurchasePrice { get; set; }
        public double? ExchangeRate { get; set; }
        public double? Margin { get; set; }
        public double? Cost { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}