// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ItemWarehouse
    {
        public int Id { get; set; }
        public int IdItem { get; set; }
        public int IdWarehouse { get; set; }
        public double? MinQuantity { get; set; }
        public double? MaxQuantity { get; set; }
        public double AvailableQuantity { get; set; }
        public double ReservedQuantity { get; set; }
        public double OnOrderQuantity { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Shelf { get; set; }
        public string Storage { get; set; }
        public double OrderedQuantity { get; set; }
        public int? IdShelf { get; set; }
        public int? IdStorage { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual Shelf IdShelfNavigation { get; set; }
        public virtual Storage IdStorageNavigation { get; set; }
        public virtual Warehouse IdWarehouseNavigation { get; set; }
    }
}