// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Item
    {
        public Item()
        {
            Claim = new HashSet<Claim>();
            Delivery = new HashSet<Delivery>();
            DocumentLine = new HashSet<DocumentLine>();
            DocumentLineNegotiationOptions = new HashSet<DocumentLineNegotiationOptions>();
            Expense = new HashSet<Expense>();
            InverseIdItemReplacementNavigation = new HashSet<Item>();
            ItemKitIdItemNavigation = new HashSet<ItemKit>();
            ItemKitIdKitNavigation = new HashSet<ItemKit>();
            ItemPrices = new HashSet<ItemPrices>();
            ItemSalesPrice = new HashSet<ItemSalesPrice>();
            ItemTiers = new HashSet<ItemTiers>();
            ItemVehicleBrandModelSubModel = new HashSet<ItemVehicleBrandModelSubModel>();
            ItemWarehouse = new HashSet<ItemWarehouse>();
            MovementHistory = new HashSet<MovementHistory>();
            OemItem = new HashSet<OemItem>();
            PriceRequestDetail = new HashSet<PriceRequestDetail>();
            ProvisioningDetails = new HashSet<ProvisioningDetails>();
            StockDocumentLine = new HashSet<StockDocumentLine>();
            StockMovement = new HashSet<StockMovement>();
            TaxeItem = new HashSet<TaxeItem>();
            TriggerItemLog = new HashSet<TriggerItemLog>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string BarCode1D { get; set; }
        public string BarCode2D { get; set; }
        public int? IdUnitStock { get; set; }
        public int? IdUnitSales { get; set; }
        public double? CoeffConversion { get; set; }
        public double? UnitHtpurchasePrice { get; set; }
        public double? UnitHtsalePrice { get; set; }
        public double? UnitTtcpurchasePrice { get; set; }
        public double? UnitTtcsalePrice { get; set; }
        public double? Tvarate { get; set; }
        public double? FixedMargin { get; set; }
        public double? VariableMargin { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdNature { get; set; }
        public Guid? EquivalenceItem { get; set; }
        public int? IdFamily { get; set; }
        public int? IdSubFamily { get; set; }
        public bool OnOrder { get; set; }
        public string Note { get; set; }
        public int? IdPolicyValorization { get; set; }
        public double? AverageSalesPerDay { get; set; }
        public int? IdAccountingAccountSales { get; set; }
        public int? IdAccountingAccountPurchase { get; set; }
        public int? TecDocId { get; set; }
        public string TecDocRef { get; set; }
        public int? TecDocIdSupplier { get; set; }
        public int? IdEmployee { get; set; }
        public bool? IsForPurchase { get; set; }
        public bool? IsForSales { get; set; }
        public bool IsKit { get; set; }
        public int? IdItemReplacement { get; set; }
        public int? IdProductItem { get; set; }
        public bool HaveClaims { get; set; }
        public double? DefaultUnitHtpurchasePrice { get; set; }
        public bool IsEcommerce { get; set; }
        public bool ExistInEcommerce { get; set; }
        public int? OnlineSynchonizationStatus { get; set; }
        public int? SynchonizationStatus { get; set; }
        public DateTime? LastUpdateEcommerce { get; set; }
        public string TecDocImageUrl { get; set; }
        public string TecDocBrandName { get; set; }
        public string UrlPicture { get; set; }
        public bool ProvInventory { get; set; }
        public bool? IsFromGarage { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public double? CostPrice { get; set; }
        public DateTime? UpdatedDatePicture { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Family IdFamilyNavigation { get; set; }
        public virtual Item IdItemReplacementNavigation { get; set; }
        public virtual Nature IdNatureNavigation { get; set; }
        public virtual ProductItem IdProductItemNavigation { get; set; }
        public virtual SubFamily IdSubFamilyNavigation { get; set; }
        public virtual MeasureUnit IdUnitSalesNavigation { get; set; }
        public virtual MeasureUnit IdUnitStockNavigation { get; set; }
        public virtual ICollection<Claim> Claim { get; set; }
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<DocumentLineNegotiationOptions> DocumentLineNegotiationOptions { get; set; }
        public virtual ICollection<Expense> Expense { get; set; }
        public virtual ICollection<Item> InverseIdItemReplacementNavigation { get; set; }
        public virtual ICollection<ItemKit> ItemKitIdItemNavigation { get; set; }
        public virtual ICollection<ItemKit> ItemKitIdKitNavigation { get; set; }
        public virtual ICollection<ItemPrices> ItemPrices { get; set; }
        public virtual ICollection<ItemSalesPrice> ItemSalesPrice { get; set; }
        public virtual ICollection<ItemTiers> ItemTiers { get; set; }
        public virtual ICollection<ItemVehicleBrandModelSubModel> ItemVehicleBrandModelSubModel { get; set; }
        public virtual ICollection<ItemWarehouse> ItemWarehouse { get; set; }
        public virtual ICollection<MovementHistory> MovementHistory { get; set; }
        public virtual ICollection<OemItem> OemItem { get; set; }
        public virtual ICollection<PriceRequestDetail> PriceRequestDetail { get; set; }
        public virtual ICollection<ProvisioningDetails> ProvisioningDetails { get; set; }
        public virtual ICollection<StockDocumentLine> StockDocumentLine { get; set; }
        public virtual ICollection<StockMovement> StockMovement { get; set; }
        public virtual ICollection<TaxeItem> TaxeItem { get; set; }
        public virtual ICollection<TriggerItemLog> TriggerItemLog { get; set; }
    }
}