// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ItemVehicleBrandModelSubModel
    {
        public int Id { get; set; }
        public int? IdItem { get; set; }
        public int? IdVehicleBrand { get; set; }
        public int? IdModel { get; set; }
        public int? IdSubModel { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual ModelOfItem IdModelNavigation { get; set; }
        public virtual SubModel IdSubModelNavigation { get; set; }
        public virtual VehicleBrand IdVehicleBrandNavigation { get; set; }
    }
}