// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ItemKit
    {
        public int Id { get; set; }
        public int? IdKit { get; set; }
        public int? IdItem { get; set; }
        public int? Quantity { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual Item IdKitNavigation { get; set; }
    }
}