// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Job
    {
        public Job()
        {
            InverseIdUpperJobNavigation = new HashSet<Job>();
            JobEmployee = new HashSet<JobEmployee>();
            JobSkills = new HashSet<JobSkills>();
            Recruitment = new HashSet<Recruitment>();
        }

        public int Id { get; set; }
        public string Designation { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string FunctionSheet { get; set; }
        public int? IdUpperJob { get; set; }
        public string HierarchyLevel { get; set; }

        public virtual Job IdUpperJobNavigation { get; set; }
        public virtual ICollection<Job> InverseIdUpperJobNavigation { get; set; }
        public virtual ICollection<JobEmployee> JobEmployee { get; set; }
        public virtual ICollection<JobSkills> JobSkills { get; set; }
        public virtual ICollection<Recruitment> Recruitment { get; set; }
    }
}