// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class JobSkills
    {
        public int Id { get; set; }
        public int IdJob { get; set; }
        public int IdSkill { get; set; }
        public int? Rate { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Job IdJobNavigation { get; set; }
        public virtual Skills IdSkillNavigation { get; set; }
    }
}