// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class JobsParameter
    {
        public int Id { get; set; }
        public string Keys { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
    }
}