// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class JobTable
    {
        public int Id { get; set; }
        public DateTime? LastExecuteDate { get; set; }
        public DateTime? NextExecuteDate { get; set; }
    }
}