// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Language
    {
        public Language()
        {
            RecruitmentLanguage = new HashSet<RecruitmentLanguage>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<RecruitmentLanguage> RecruitmentLanguage { get; set; }
    }
}