// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class LeaveBalanceRemaining
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdLeaveType { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public double RemainingBalanceDay { get; set; }
        public double RemainingBalanceHour { get; set; }
        public double CumulativeTakenDay { get; set; }
        public double CumulativeTakenHour { get; set; }
        public double CumulativeAcquiredDay { get; set; }
        public double CumulativeAcquiredHour { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual LeaveType IdLeaveTypeNavigation { get; set; }
    }
}