// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class LeaveType
    {
        public LeaveType()
        {
            ExitEmployeeLeaveLine = new HashSet<ExitEmployeeLeaveLine>();
            Leave = new HashSet<Leave>();
            LeaveBalanceRemaining = new HashSet<LeaveBalanceRemaining>();
        }

        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public bool Paid { get; set; }
        public bool RequiredDocument { get; set; }
        public string Description { get; set; }
        public int MaximumNumberOfDays { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public bool Calendar { get; set; }
        public bool? Cumulable { get; set; }
        public bool AuthorizedOvertaking { get; set; }
        public int Period { get; set; }
        public bool Worked { get; set; }

        public virtual ICollection<ExitEmployeeLeaveLine> ExitEmployeeLeaveLine { get; set; }
        public virtual ICollection<Leave> Leave { get; set; }
        public virtual ICollection<LeaveBalanceRemaining> LeaveBalanceRemaining { get; set; }
    }
}