// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Leave
    {
        public Leave()
        {
            LeaveEmail = new HashSet<LeaveEmail>();
            TimeSheetLine = new HashSet<TimeSheetLine>();
        }

        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdEmployee { get; set; }
        public int IdLeaveType { get; set; }
        public int Status { get; set; }
        public double DaysNumber { get; set; }
        public double HoursNumber { get; set; }
        public string Description { get; set; }
        public string LeaveAttachementFile { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int? TreatedBy { get; set; }
        public string Code { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual LeaveType IdLeaveTypeNavigation { get; set; }
        public virtual Employee TreatedByNavigation { get; set; }
        public virtual ICollection<LeaveEmail> LeaveEmail { get; set; }
        public virtual ICollection<TimeSheetLine> TimeSheetLine { get; set; }
    }
}