// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Loan
    {
        public Loan()
        {
            LoanInstallment = new HashSet<LoanInstallment>();
        }

        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? State { get; set; }
        public string Code { get; set; }
        public DateTime? DisbursementDate { get; set; }
        public DateTime? ApprouvementDate { get; set; }
        public double Amount { get; set; }
        public DateTime ObtainingDate { get; set; }
        public int IdEmployee { get; set; }
        public string Reason { get; set; }
        public string LoanAttachementFile { get; set; }
        public int MonthsNumber { get; set; }
        public DateTime? RefundStartDate { get; set; }
        public int? CreditType { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual ICollection<LoanInstallment> LoanInstallment { get; set; }
    }
}