// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Log
    {
        public int IdDbrequest { get; set; }
        public DateTime? DateOfRequest { get; set; }
        public string Object { get; set; }
        public string RequestName { get; set; }
        public int? TrasactionIdUser { get; set; }
        public bool IsDeleted { get; set; }
        public int? LogInt1 { get; set; }
        public int? LogInt2 { get; set; }
        public int? LogInt3 { get; set; }
        public int? LogInt4 { get; set; }
        public int? LogInt5 { get; set; }
        public int? LogInt6 { get; set; }
        public int? LogInt7 { get; set; }
        public int? LogInt8 { get; set; }
        public int? LogInt9 { get; set; }
        public int? LogInt10 { get; set; }
        public bool? LogBit1 { get; set; }
        public bool? LogBit2 { get; set; }
        public bool? LogBit3 { get; set; }
        public bool? LogBit4 { get; set; }
        public bool? LogBit5 { get; set; }
        public bool? LogBit6 { get; set; }
        public bool? LogBit7 { get; set; }
        public bool? LogBit8 { get; set; }
        public bool? LogBit9 { get; set; }
        public bool? LogBit10 { get; set; }
        public double? LogFloat1 { get; set; }
        public double? LogFloat2 { get; set; }
        public double? LogFloat3 { get; set; }
        public double? LogFloat4 { get; set; }
        public double? LogFloat5 { get; set; }
        public double? LogFloat6 { get; set; }
        public double? LogFloat7 { get; set; }
        public double? LogFloat8 { get; set; }
        public double? LogFloat9 { get; set; }
        public double? LogFloat10 { get; set; }
        public string LogVarchar1 { get; set; }
        public string LogVarchar2 { get; set; }
        public string LogVarchar3 { get; set; }
        public string LogVarchar4 { get; set; }
        public string LogVarchar5 { get; set; }
        public string LogVarchar6 { get; set; }
        public string LogVarchar7 { get; set; }
        public string LogVarchar8 { get; set; }
        public string LogVarchar9 { get; set; }
        public string LogVarchar10 { get; set; }
        public DateTime? LogDate1 { get; set; }
        public DateTime? LogDate2 { get; set; }
        public DateTime? LogDate3 { get; set; }
        public DateTime? LogDate4 { get; set; }
        public DateTime? LogDate5 { get; set; }
        public DateTime? LogDate6 { get; set; }
        public DateTime? LogDate7 { get; set; }
        public DateTime? LogDate8 { get; set; }
        public DateTime? LogDate9 { get; set; }
        public DateTime? LogDate10 { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
    }
}