// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class MeasureUnit
    {
        public MeasureUnit()
        {
            DocumentLine = new HashSet<DocumentLine>();
            ItemIdUnitSalesNavigation = new HashSet<Item>();
            ItemIdUnitStockNavigation = new HashSet<Item>();
        }

        public int Id { get; set; }
        public string MeasureUnitCode { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDecomposable { get; set; }
        public int DigitsAfterComma { get; set; }

        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<Item> ItemIdUnitSalesNavigation { get; set; }
        public virtual ICollection<Item> ItemIdUnitStockNavigation { get; set; }
    }
}