// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Message
    {
        public Message()
        {
            MsgNotification = new HashSet<MsgNotification>();
        }

        public int Id { get; set; }
        public int IdCreator { get; set; }
        public int IdInformation { get; set; }
        public int EntityReference { get; set; }
        public string CodeEntity { get; set; }
        public int? TypeMessage { get; set; }

        public virtual Information IdInformationNavigation { get; set; }
        public virtual ICollection<MsgNotification> MsgNotification { get; set; }
    }
}