// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class MessageChat
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public DateTime Date { get; set; }
        public string AttachedFilesLink { get; set; }
        public int IdUserDiscussion { get; set; }

        public virtual UserDiscussionChat IdUserDiscussionNavigation { get; set; }
    }
}