// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class MobilityRequest
    {
        public int Id { get; set; }
        public int? Status { get; set; }
        public int IdEmployee { get; set; }
        public int IdCurrentOffice { get; set; }
        public int IdDestinationOffice { get; set; }
        public DateTime DesiredMobilityDate { get; set; }
        public DateTime? EffectifMobilityDate { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public int? IdCreationUser { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual User IdCreationUserNavigation { get; set; }
        public virtual Office IdCurrentOfficeNavigation { get; set; }
        public virtual Office IdDestinationOfficeNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
    }
}