// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ModelOfItem
    {
        public ModelOfItem()
        {
            ItemVehicleBrandModelSubModel = new HashSet<ItemVehicleBrandModelSubModel>();
            SubModel = new HashSet<SubModel>();
            Vehicle = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public int? IdVehicleBrand { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public string UrlPicture { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual VehicleBrand IdVehicleBrandNavigation { get; set; }
        public virtual ICollection<ItemVehicleBrandModelSubModel> ItemVehicleBrandModelSubModel { get; set; }
        public virtual ICollection<SubModel> SubModel { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}