// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class MsgNotification
    {
        public int Id { get; set; }
        public int IdMsg { get; set; }
        public int IdTargetedUser { get; set; }
        public bool Viewed { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public DateTime? CreationDate { get; set; }

        public virtual Message IdMsgNavigation { get; set; }
    }
}