// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class NewUserEmail
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdEmail { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Email IdEmailNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
    }
}