// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Notification
    {
        public int IdNotification { get; set; }
        public string Fr { get; set; }
        public string En { get; set; }
        public string Ar { get; set; }
        public string De { get; set; }
        public string Ch { get; set; }
        public string Es { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
    }
}