// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Objective
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public DateTime ExpectedDate { get; set; }
        public int? ObjectiveCollaboratorStatus { get; set; }
        public int? ObjectiveManagerStatus { get; set; }
        public string DescriptionCollaborator { get; set; }
        public string DescriptionManager { get; set; }
        public DateTime? RealisationDate { get; set; }
        public int IdReview { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdEmployee { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Review IdReviewNavigation { get; set; }
    }
}