// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Offer
    {
        public Offer()
        {
            Advantages = new HashSet<Advantages>();
            OfferBenefitInKind = new HashSet<OfferBenefitInKind>();
            OfferBonus = new HashSet<OfferBonus>();
        }

        public int Id { get; set; }
        public int State { get; set; }
        public int IdCandidacy { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public double WorkingHoursPerWeek { get; set; }
        public double Salary { get; set; }
        public bool? ThirteenthMonthBonus { get; set; }
        public int IdSalaryStructure { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? SendingDate { get; set; }
        public int? IdEmail { get; set; }
        public int IdCnss { get; set; }
        public int IdContractType { get; set; }
        public string Token { get; set; }
        public double? MealVoucher { get; set; }
        public bool? AvailableCar { get; set; }
        public bool? AvailableHouse { get; set; }
        public int? CommissionType { get; set; }
        public double? CommissionValue { get; set; }

        public virtual Candidacy IdCandidacyNavigation { get; set; }
        public virtual Cnss IdCnssNavigation { get; set; }
        public virtual ContractType IdContractTypeNavigation { get; set; }
        public virtual Email IdEmailNavigation { get; set; }
        public virtual SalaryStructure IdSalaryStructureNavigation { get; set; }
        public virtual ICollection<Advantages> Advantages { get; set; }
        public virtual ICollection<OfferBenefitInKind> OfferBenefitInKind { get; set; }
        public virtual ICollection<OfferBonus> OfferBonus { get; set; }
    }
}