// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Office
    {
        public Office()
        {
            Address = new HashSet<Address>();
            Contact = new HashSet<Contact>();
            Employee = new HashSet<Employee>();
            MobilityRequestIdCurrentOfficeNavigation = new HashSet<MobilityRequest>();
            MobilityRequestIdDestinationOfficeNavigation = new HashSet<MobilityRequest>();
            Recruitment = new HashSet<Recruitment>();
        }

        public int Id { get; set; }
        public string OfficeName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string PhoneNumber { get; set; }
        public string Facebook { get; set; }
        public string LinkedIn { get; set; }
        public int? IdOfficeManager { get; set; }
        public int? IdCreationUser { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public DateTime CreationDate { get; set; }
        public int TransactionUserId { get; set; }
        public string Twitter { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<MobilityRequest> MobilityRequestIdCurrentOfficeNavigation { get; set; }
        public virtual ICollection<MobilityRequest> MobilityRequestIdDestinationOfficeNavigation { get; set; }
        public virtual ICollection<Recruitment> Recruitment { get; set; }
    }
}