// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class OperationCash
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string AgentCode { get; set; }
        public int IdSession { get; set; }
        public DateTime OperationDate { get; set; }
        public double Amount { get; set; }
        public double AmountWithCurrency { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int TransactionUserId { get; set; }

        public virtual SessionCash IdSessionNavigation { get; set; }
    }
}