// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PaymentSlip
    {
        public PaymentSlip()
        {
            Settlement = new HashSet<Settlement>();
        }

        public int Id { get; set; }
        public string Reference { get; set; }
        public string Agency { get; set; }
        public string Deposer { get; set; }
        public DateTime Date { get; set; }
        public int? IdBankAccount { get; set; }
        public double? TotalAmountWithNumbers { get; set; }
        public string TotalAmountWithLetters { get; set; }
        public int? State { get; set; }
        public string Type { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
    }
}