// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            DetailTimetable = new HashSet<DetailTimetable>();
            Employee = new HashSet<Employee>();
            PaymentMethod = new HashSet<PaymentMethod>();
            TicketPayment = new HashSet<TicketPayment>();
            Timetable = new HashSet<Timetable>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? PaymentTypeInt1 { get; set; }
        public int? PaymentTypeInt2 { get; set; }
        public int? PaymentTypeInt3 { get; set; }
        public int? PaymentTypeInt4 { get; set; }
        public int? PaymentTypeInt5 { get; set; }
        public int? PaymentTypeInt6 { get; set; }
        public int? PaymentTypeInt7 { get; set; }
        public int? PaymentTypeInt8 { get; set; }
        public int? PaymentTypeInt9 { get; set; }
        public int? PaymentTypeInt10 { get; set; }
        public bool? PaymentTypeBit1 { get; set; }
        public bool? PaymentTypeBit2 { get; set; }
        public bool? PaymentTypeBit3 { get; set; }
        public bool? PaymentTypeBit4 { get; set; }
        public bool? PaymentTypeBit5 { get; set; }
        public bool? PaymentTypeBit6 { get; set; }
        public bool? PaymentTypeBit7 { get; set; }
        public bool? PaymentTypeBit8 { get; set; }
        public bool? PaymentTypeBit9 { get; set; }
        public bool? PaymentTypeBit10 { get; set; }
        public double? PaymentTypeFloat1 { get; set; }
        public double? PaymentTypeFloat2 { get; set; }
        public double? PaymentTypeFloat3 { get; set; }
        public double? PaymentTypeFloat4 { get; set; }
        public double? PaymentTypeFloat5 { get; set; }
        public double? PaymentTypeFloat6 { get; set; }
        public double? PaymentTypeFloat7 { get; set; }
        public double? PaymentTypeFloat8 { get; set; }
        public double? PaymentTypeFloat9 { get; set; }
        public double? PaymentTypeFloat10 { get; set; }
        public string PaymentTypeVarchar1 { get; set; }
        public string PaymentTypeVarchar2 { get; set; }
        public string PaymentTypeVarchar3 { get; set; }
        public string PaymentTypeVarchar4 { get; set; }
        public string PaymentTypeVarchar5 { get; set; }
        public string PaymentTypeVarchar6 { get; set; }
        public string PaymentTypeVarchar7 { get; set; }
        public string PaymentTypeVarchar8 { get; set; }
        public string PaymentTypeVarchar9 { get; set; }
        public string PaymentTypeVarchar10 { get; set; }
        public DateTime? PaymentTypeDate1 { get; set; }
        public DateTime? PaymentTypeDate2 { get; set; }
        public DateTime? PaymentTypeDate3 { get; set; }
        public DateTime? PaymentTypeDate4 { get; set; }
        public DateTime? PaymentTypeDate5 { get; set; }
        public DateTime? PaymentTypeDate6 { get; set; }
        public DateTime? PaymentTypeDate7 { get; set; }
        public DateTime? PaymentTypeDate8 { get; set; }
        public DateTime? PaymentTypeDate9 { get; set; }
        public DateTime? PaymentTypeDate10 { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }

        public virtual ICollection<DetailTimetable> DetailTimetable { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethod { get; set; }
        public virtual ICollection<TicketPayment> TicketPayment { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
    }
}