// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PaymentCondition
    {
        public PaymentCondition()
        {
            Tiers = new HashSet<Tiers>();
        }

        public int Id { get; set; }
        public int? Nbr { get; set; }
        public string Designation { get; set; }
        public string Unit { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? PaymentConditionInt1 { get; set; }
        public int? PaymentConditionInt2 { get; set; }
        public int? PaymentConditionInt3 { get; set; }
        public int? PaymentConditionInt4 { get; set; }
        public int? PaymentConditionInt5 { get; set; }
        public int? PaymentConditionInt6 { get; set; }
        public int? PaymentConditionInt7 { get; set; }
        public int? PaymentConditionInt8 { get; set; }
        public int? PaymentConditionInt9 { get; set; }
        public int? PaymentConditionInt10 { get; set; }
        public bool? PaymentConditionBit1 { get; set; }
        public bool? PaymentConditionBit2 { get; set; }
        public bool? PaymentConditionBit3 { get; set; }
        public bool? PaymentConditionBit4 { get; set; }
        public bool? PaymentConditionBit5 { get; set; }
        public bool? PaymentConditionBit6 { get; set; }
        public bool? PaymentConditionBit7 { get; set; }
        public bool? PaymentConditionBit8 { get; set; }
        public bool? PaymentConditionBit9 { get; set; }
        public bool? PaymentConditionBit10 { get; set; }
        public double? PaymentConditionFloat1 { get; set; }
        public double? PaymentConditionFloat2 { get; set; }
        public double? PaymentConditionFloat3 { get; set; }
        public double? PaymentConditionFloat4 { get; set; }
        public double? PaymentConditionFloat5 { get; set; }
        public double? PaymentConditionFloat6 { get; set; }
        public double? PaymentConditionFloat7 { get; set; }
        public double? PaymentConditionFloat8 { get; set; }
        public double? PaymentConditionFloat9 { get; set; }
        public double? PaymentConditionFloat10 { get; set; }
        public string PaymentConditionVarchar1 { get; set; }
        public string PaymentConditionVarchar2 { get; set; }
        public string PaymentConditionVarchar3 { get; set; }
        public string PaymentConditionVarchar4 { get; set; }
        public string PaymentConditionVarchar5 { get; set; }
        public string PaymentConditionVarchar6 { get; set; }
        public string PaymentConditionVarchar7 { get; set; }
        public string PaymentConditionVarchar8 { get; set; }
        public string PaymentConditionVarchar9 { get; set; }
        public string PaymentConditionVarchar10 { get; set; }
        public DateTime? PaymentConditionDate1 { get; set; }
        public DateTime? PaymentConditionDate2 { get; set; }
        public DateTime? PaymentConditionDate3 { get; set; }
        public DateTime? PaymentConditionDate4 { get; set; }
        public DateTime? PaymentConditionDate5 { get; set; }
        public DateTime? PaymentConditionDate6 { get; set; }
        public DateTime? PaymentConditionDate7 { get; set; }
        public DateTime? PaymentConditionDate8 { get; set; }
        public DateTime? PaymentConditionDate9 { get; set; }
        public DateTime? PaymentConditionDate10 { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Tiers> Tiers { get; set; }
    }
}