// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Payslip
    {
        public Payslip()
        {
            PayslipDetails = new HashSet<PayslipDetails>();
        }

        public int Id { get; set; }
        public int IdContract { get; set; }
        public int IdEmployee { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdSession { get; set; }
        public int Status { get; set; }
        public string ErrorMessage { get; set; }
        public DateTime Month { get; set; }
        public int? IdTransferOrder { get; set; }

        public virtual Contract IdContractNavigation { get; set; }
        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Session IdSessionNavigation { get; set; }
        public virtual TransferOrder IdTransferOrderNavigation { get; set; }
        public virtual ICollection<PayslipDetails> PayslipDetails { get; set; }
    }
}