// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Period
    {
        public Period()
        {
            DayOff = new HashSet<DayOff>();
            Hours = new HashSet<Hours>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int FirstDayOfWork { get; set; }
        public int LastDayOfWork { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<DayOff> DayOff { get; set; }
        public virtual ICollection<Hours> Hours { get; set; }
    }
}