// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Phone
    {
        public Phone()
        {
            Bank = new HashSet<Bank>();
            Tiers = new HashSet<Tiers>();
            User = new HashSet<User>();
        }

        public int Id { get; set; }
        public int? Number { get; set; }
        public string DialCode { get; set; }
        public string CountryCode { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdContact { get; set; }

        public virtual Contact IdContactNavigation { get; set; }
        public virtual ICollection<Bank> Bank { get; set; }
        public virtual ICollection<Tiers> Tiers { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}