// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Prices
    {
        public Prices()
        {
            DocumentLine = new HashSet<DocumentLine>();
            DocumentLinePrices = new HashSet<DocumentLinePrices>();
            ItemPrices = new HashSet<ItemPrices>();
            PriceDetail = new HashSet<PriceDetail>();
            TiersPrices = new HashSet<TiersPrices>();
        }

        public int Id { get; set; }
        public string LabelPrices { get; set; }
        public string CodePrices { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdUsedCurrency { get; set; }
        public string DeletedToken { get; set; }
        public string AttachmentUrl { get; set; }
        public string ContractCode { get; set; }

        public virtual Currency IdUsedCurrencyNavigation { get; set; }
        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<DocumentLinePrices> DocumentLinePrices { get; set; }
        public virtual ICollection<ItemPrices> ItemPrices { get; set; }
        public virtual ICollection<PriceDetail> PriceDetail { get; set; }
        public virtual ICollection<TiersPrices> TiersPrices { get; set; }
    }
}