// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PriceRequest
    {
        public PriceRequest()
        {
            Document = new HashSet<Document>();
            PriceRequestDetail = new HashSet<PriceRequestDetail>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Reference { get; set; }
        public DateTime DocumentDate { get; set; }
        public DateTime CreationDate { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<PriceRequestDetail> PriceRequestDetail { get; set; }
    }
}