// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PriceRequestDetail
    {
        public int Id { get; set; }
        public int IdPriceRequest { get; set; }
        public int IdItem { get; set; }
        public string Designation { get; set; }
        public double MovementQty { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public int IdTiers { get; set; }
        public int? IdContact { get; set; }

        public virtual Contact IdContactNavigation { get; set; }
        public virtual Item IdItemNavigation { get; set; }
        public virtual PriceRequest IdPriceRequestNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}