// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PriceDetail
    {
        public int Id { get; set; }
        public int IdPrices { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public double? Percentage { get; set; }
        public double? ReducedValue { get; set; }
        public double? SpecialPrice { get; set; }
        public double? MinimumQuantity { get; set; }
        public double? MaximumQuantity { get; set; }
        public double? TotalPrices { get; set; }
        public double? SaledItemsNumber { get; set; }
        public double? GiftedItemsNumber { get; set; }
        public int TypeOfPriceDetail { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Prices IdPricesNavigation { get; set; }
    }
}