// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ProductItem
    {
        public ProductItem()
        {
            Item = new HashSet<Item>();
        }

        public int Id { get; set; }
        public string CodeProduct { get; set; }
        public string LabelProduct { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public string UrlPicture { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<Item> Item { get; set; }
    }
}