// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Project
    {
        public Project()
        {
            BillingEmployee = new HashSet<BillingEmployee>();
            EmployeeProject = new HashSet<EmployeeProject>();
            TimeSheetLine = new HashSet<TimeSheetLine>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ExpectedEndDate { get; set; }
        public int ProjectType { get; set; }
        public int? IdTaxe { get; set; }
        public double? AverageDailyRate { get; set; }
        public int? IdTiers { get; set; }
        public int? IdSettlementMode { get; set; }
        public bool Default { get; set; }
        public int? IdContact { get; set; }
        public int? IdCurrency { get; set; }
        public bool IsBillable { get; set; }
        public string ReferenceProject { get; set; }
        public string ReferenceBc { get; set; }
        public string LabelInInvoice { get; set; }
        public int? IdBankAccount { get; set; }
        public string ProjectLabel { get; set; }
        public string AttachementFile { get; set; }
        public DateTime CreationDate { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual Contact IdContactNavigation { get; set; }
        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual SettlementMode IdSettlementModeNavigation { get; set; }
        public virtual Taxe IdTaxeNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual ICollection<BillingEmployee> BillingEmployee { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProject { get; set; }
        public virtual ICollection<TimeSheetLine> TimeSheetLine { get; set; }
    }
}