// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ProvisioningOption
    {
        public ProvisioningOption()
        {
            Provisioning = new HashSet<Provisioning>();
        }

        public int Id { get; set; }
        public bool SearchByQty { get; set; }
        public bool SearchByPurhaseHistory { get; set; }
        public bool SearchBySalesHistory { get; set; }
        public DateTime? PucrahseStartDate { get; set; }
        public DateTime? PucrahseEndDate { get; set; }
        public DateTime? SalesStartDate { get; set; }
        public DateTime? SalesEndDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int TransactionUserId { get; set; }
        public bool SearchByNewReferences { get; set; }
        public DateTime? NewReferencesStartDate { get; set; }
        public DateTime? NewReferencesEndDate { get; set; }

        public virtual ICollection<Provisioning> Provisioning { get; set; }
    }
}