// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ProvisioningDetails
    {
        public int Id { get; set; }
        public int IdProvisioning { get; set; }
        public int IdItem { get; set; }
        public int IdTiers { get; set; }
        public double? MvtQty { get; set; }
        public double? LastePurchasePrice { get; set; }
        public int TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Item IdItemNavigation { get; set; }
        public virtual Provisioning IdProvisioningNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}