// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Provisioning
    {
        public Provisioning()
        {
            Document = new HashSet<Document>();
            ProvisioningDetails = new HashSet<ProvisioningDetails>();
            TiersProvisioning = new HashSet<TiersProvisioning>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public DateTime? ProjectDate { get; set; }
        public DateTime? CreationDate { get; set; }
        public int IdProvisioningOption { get; set; }
        public bool IsPurchaseOrderGenerated { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int TransactionUserId { get; set; }

        public virtual ProvisioningOption IdProvisioningOptionNavigation { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<ProvisioningDetails> ProvisioningDetails { get; set; }
        public virtual ICollection<TiersProvisioning> TiersProvisioning { get; set; }
    }
}