// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class PurchaseSettings
    {
        public int Id { get; set; }
        public double? PurchaseOtherTaxes { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdPurchasingManager { get; set; }
        public bool? PurchaseAllowItemManagedInStock { get; set; }
        public bool? PurchaseAllowItemRelatedToSupplier { get; set; }

        public virtual Company IdNavigation { get; set; }
        public virtual User IdPurchasingManagerNavigation { get; set; }
    }
}