// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class QualificationType
    {
        public QualificationType()
        {
            Qualification = new HashSet<Qualification>();
            Recruitment = new HashSet<Recruitment>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Qualification> Qualification { get; set; }
        public virtual ICollection<Recruitment> Recruitment { get; set; }
    }
}