// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Question
    {
        public int Id { get; set; }
        public string QuestionLabel { get; set; }
        public string ResponseLabel { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdInterview { get; set; }

        public virtual Interview IdInterviewNavigation { get; set; }
    }
}