// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ReceiptSpent
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public int? IdTiers { get; set; }
        public string Activity { get; set; }
        public double? ProvisionalAmount { get; set; }
        public int? IdPaymentMethod { get; set; }
        public DateTime? Deadline { get; set; }
        public int? IdBankAccount { get; set; }
        public int? IdCaisse { get; set; }
        public int? IdPaymentDirection { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string Periodicity { get; set; }
        public int? PeriodsNumber { get; set; }
        public int? IdReceiptSpentAxis1 { get; set; }
        public int? IdReceiptSpentAxis2 { get; set; }
        public int? IdReceiptSpentAxis3 { get; set; }
        public int? IdReceiptSpentAxis4 { get; set; }
        public int? IdReceiptSpentAxis5 { get; set; }
        public int? IdReceiptSpentAxis6 { get; set; }
        public int? IdReceiptSpentAxis7 { get; set; }
        public int? IdReceiptSpentAxis8 { get; set; }
        public int? IdReceiptSpentAxis9 { get; set; }
        public int? IdReceiptSpentAxis10 { get; set; }
        public int? IdReceiptSpentAxis11 { get; set; }
        public int? IdReceiptSpentAxis12 { get; set; }
        public int? IdReceiptSpentAxis13 { get; set; }
        public int? IdReceiptSpentAxis14 { get; set; }
        public int? IdReceiptSpentAxis15 { get; set; }
        public int? IdReceiptSpentAxis16 { get; set; }
        public int? IdReceiptSpentAxis17 { get; set; }
        public int? IdReceiptSpentAxis18 { get; set; }
        public int? IdReceiptSpentAxis19 { get; set; }
        public int? IdReceiptSpentAxis20 { get; set; }
        public int? IdReceiptSpentAxis21 { get; set; }
        public int? IdReceiptSpentAxis22 { get; set; }
        public int? IdReceiptSpentAxis23 { get; set; }
        public int? IdReceiptSpentAxis24 { get; set; }
        public int? IdReceiptSpentAxis25 { get; set; }
        public int? IdReceiptSpentAxis26 { get; set; }
        public int? IdReceiptSpentAxis27 { get; set; }
        public int? IdReceiptSpentAxis28 { get; set; }
        public int? IdReceiptSpentAxis29 { get; set; }
        public int? IdReceiptSpentAxis30 { get; set; }
        public string DeletedToken { get; set; }

        public virtual PaymentDirection IdPaymentDirectionNavigation { get; set; }
        public virtual PaymentMethod IdPaymentMethodNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}