// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Reconciliation
    {
        public Reconciliation()
        {
            DetailReconciliation = new HashSet<DetailReconciliation>();
            Settlement = new HashSet<Settlement>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public DateTime ReconciliationDate { get; set; }
        public int IdBankAccount { get; set; }
        public bool? IsValidate { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string AttachmentUrl { get; set; }
        public double? TotalDebit { get; set; }
        public double? TotalCredit { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual ICollection<DetailReconciliation> DetailReconciliation { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
    }
}