// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Recruitment
    {
        public Recruitment()
        {
            Candidacy = new HashSet<Candidacy>();
            RecruitmentLanguage = new HashSet<RecruitmentLanguage>();
            RecruitmentSkills = new HashSet<RecruitmentSkills>();
        }

        public int Id { get; set; }
        public int? YearOfExperience { get; set; }
        public double? WorkingHoursPerDays { get; set; }
        public int Priority { get; set; }
        public string Description { get; set; }
        public int State { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? ClosingDate { get; set; }
        public int IdQualificationType { get; set; }
        public int IdJob { get; set; }
        public int? IdEmployeeAuthor { get; set; }
        public int? IdEmployeeValidator { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdOffice { get; set; }
        public string RequestReason { get; set; }
        public int? ExpectedCandidateNumber { get; set; }
        public DateTime? StartDate { get; set; }
        public int? IdContractType { get; set; }
        public int? Type { get; set; }
        public int? RequestStatus { get; set; }
        public int Sex { get; set; }
        public string Code { get; set; }
        public int? OfferStatus { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string OfferPicture { get; set; }
        public string RecruitmentTypeCode { get; set; }
        public int RecruitedCandidateNumber { get; set; }

        public virtual ContractType IdContractTypeNavigation { get; set; }
        public virtual Employee IdEmployeeAuthorNavigation { get; set; }
        public virtual Employee IdEmployeeValidatorNavigation { get; set; }
        public virtual Job IdJobNavigation { get; set; }
        public virtual Office IdOfficeNavigation { get; set; }
        public virtual QualificationType IdQualificationTypeNavigation { get; set; }
        public virtual ICollection<Candidacy> Candidacy { get; set; }
        public virtual ICollection<RecruitmentLanguage> RecruitmentLanguage { get; set; }
        public virtual ICollection<RecruitmentSkills> RecruitmentSkills { get; set; }
    }
}