// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class RecruitmentSkills
    {
        public int Id { get; set; }
        public int IdSkills { get; set; }
        public int IdRecruitment { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int Rate { get; set; }

        public virtual Recruitment IdRecruitmentNavigation { get; set; }
        public virtual Skills IdSkillsNavigation { get; set; }
    }
}