// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ReflectiveSettlement
    {
        public int Id { get; set; }
        public int IdSettlement { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdGapSettlement { get; set; }

        public virtual Settlement IdGapSettlementNavigation { get; set; }
        public virtual Settlement IdSettlementNavigation { get; set; }
    }
}