// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ReportTemplate
    {
        public int Id { get; set; }
        public int? IdEntity { get; set; }
        public string TemplateCode { get; set; }
        public string TemplateNameFr { get; set; }
        public string TemplateNameEn { get; set; }
        public string ReportCode { get; set; }
        public string ReportName { get; set; }

        public virtual Entity IdEntityNavigation { get; set; }
    }
}