// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// Table contains all the types of the features
    /// </summary>
    public partial class RequestType
    {
        public RequestType()
        {
            Functionality = new HashSet<Functionality>();
        }

        /// <summary>
        /// Unique identifier for Request type
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Name of request type
        /// </summary>
        public string RequestName { get; set; }
        public string RequestFile { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Functionality> Functionality { get; set; }
    }
}