// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Review
    {
        public Review()
        {
            Interview = new HashSet<Interview>();
            Objective = new HashSet<Objective>();
            ReviewFormation = new HashSet<ReviewFormation>();
            ReviewResume = new HashSet<ReviewResume>();
            ReviewSkills = new HashSet<ReviewSkills>();
        }

        public int Id { get; set; }
        public DateTime ReviewDate { get; set; }
        public int State { get; set; }
        public int IdEmployeeCollaborator { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdManager { get; set; }
        public int? FormManager { get; set; }
        public int? FormEmployee { get; set; }

        public virtual Employee IdEmployeeCollaboratorNavigation { get; set; }
        public virtual Employee IdManagerNavigation { get; set; }
        public virtual ICollection<Interview> Interview { get; set; }
        public virtual ICollection<Objective> Objective { get; set; }
        public virtual ICollection<ReviewFormation> ReviewFormation { get; set; }
        public virtual ICollection<ReviewResume> ReviewResume { get; set; }
        public virtual ICollection<ReviewSkills> ReviewSkills { get; set; }
    }
}