// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ReviewSkills
    {
        public int Id { get; set; }
        public int? CollaboratorMark { get; set; }
        public int? ManagerMark { get; set; }
        public int IdReview { get; set; }
        public int IdSkills { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdEmployee { get; set; }
        public bool IsOld { get; set; }
        public int? OldRate { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Review IdReviewNavigation { get; set; }
        public virtual Skills IdSkillsNavigation { get; set; }
    }
}