// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ReviewFormation
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? FormationCollaboratorStatus { get; set; }
        public int? FormationManagerStatus { get; set; }
        public int IdReview { get; set; }
        public int IdFormation { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string ManagerComment { get; set; }
        public string CollaboratorComment { get; set; }
        public int IdEmployee { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Formation IdFormationNavigation { get; set; }
        public virtual Review IdReviewNavigation { get; set; }
    }
}