// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class RuleUniqueReference
    {
        public RuleUniqueReference()
        {
            ConstantRate = new HashSet<ConstantRate>();
            ConstantValue = new HashSet<ConstantValue>();
            SalaryRule = new HashSet<SalaryRule>();
            Variable = new HashSet<Variable>();
        }

        public int Id { get; set; }
        public string Reference { get; set; }
        public int Type { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<ConstantRate> ConstantRate { get; set; }
        public virtual ICollection<ConstantValue> ConstantValue { get; set; }
        public virtual ICollection<SalaryRule> SalaryRule { get; set; }
        public virtual ICollection<Variable> Variable { get; set; }
    }
}