// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SalaryStructureValidityPeriod
    {
        public SalaryStructureValidityPeriod()
        {
            SalaryStructureValidityPeriodSalaryRule = new HashSet<SalaryStructureValidityPeriodSalaryRule>();
        }

        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public int IdSalaryStructure { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? TransactionUserId { get; set; }
        public int? State { get; set; }

        public virtual SalaryStructure IdSalaryStructureNavigation { get; set; }
        public virtual ICollection<SalaryStructureValidityPeriodSalaryRule> SalaryStructureValidityPeriodSalaryRule { get; set; }
    }
}