// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SalaryRule
    {
        public SalaryRule()
        {
            ExitEmployeePayLineSalaryRule = new HashSet<ExitEmployeePayLineSalaryRule>();
            PayslipDetails = new HashSet<PayslipDetails>();
            SalaryRuleValidityPeriod = new HashSet<SalaryRuleValidityPeriod>();
            SalaryStructureValidityPeriodSalaryRule = new HashSet<SalaryStructureValidityPeriodSalaryRule>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public int RuleType { get; set; }
        public bool AppearsOnPaySlip { get; set; }
        public int Applicability { get; set; }
        public int RuleCategory { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdContributionRegister { get; set; }
        public int IdRuleUniqueReference { get; set; }
        public bool DependNumberDaysWorked { get; set; }
        public bool? UsedinNewsPaper { get; set; }

        public virtual ContributionRegister IdContributionRegisterNavigation { get; set; }
        public virtual RuleUniqueReference IdRuleUniqueReferenceNavigation { get; set; }
        public virtual ICollection<ExitEmployeePayLineSalaryRule> ExitEmployeePayLineSalaryRule { get; set; }
        public virtual ICollection<PayslipDetails> PayslipDetails { get; set; }
        public virtual ICollection<SalaryRuleValidityPeriod> SalaryRuleValidityPeriod { get; set; }
        public virtual ICollection<SalaryStructureValidityPeriodSalaryRule> SalaryStructureValidityPeriodSalaryRule { get; set; }
    }
}