// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SaleSettings
    {
        public int Id { get; set; }
        public double? SaleOtherTaxes { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? InvoicingDay { get; set; }
        public bool? InvoicingEndMonth { get; set; }
        public bool? SaleAllowItemManagedInStock { get; set; }
        public bool AllowEditionItemDesignation { get; set; }

        public virtual Company IdNavigation { get; set; }
    }
}