// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SearchItem
    {
        public int Id { get; set; }
        public int IdTiers { get; set; }
        public DateTime? Date { get; set; }
        public string SearchMethod { get; set; }
        public int IdCashier { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual User IdCashierNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
    }
}