// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SessionCash
    {
        public SessionCash()
        {
            Document = new HashSet<Document>();
            OperationCash = new HashSet<OperationCash>();
            Settlement = new HashSet<Settlement>();
            Ticket = new HashSet<Ticket>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public int IdCashRegister { get; set; }
        public DateTime OpeningDate { get; set; }
        public string LastCounter { get; set; }
        public int IdSeller { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int State { get; set; }
        public DateTime? ClosingDate { get; set; }
        public double OpeningAmount { get; set; }
        public double ClosingAmount { get; set; }
        public double ClosingCashAmount { get; set; }
        public double CalculatedTotalAmount { get; set; }

        public virtual CashRegister IdCashRegisterNavigation { get; set; }
        public virtual User IdSellerNavigation { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<OperationCash> OperationCash { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}