// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Session
    {
        public Session()
        {
            Attendance = new HashSet<Attendance>();
            CnssDeclarationSession = new HashSet<CnssDeclarationSession>();
            Payslip = new HashSet<Payslip>();
            SessionBonus = new HashSet<SessionBonus>();
            SessionContract = new HashSet<SessionContract>();
            SessionLoanInstallment = new HashSet<SessionLoanInstallment>();
            TransferOrderSession = new HashSet<TransferOrderSession>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime Month { get; set; }
        public int State { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public bool DependOnTimesheet { get; set; }
        public double DaysOfWork { get; set; }
        public string Code { get; set; }
        public string DaysWorkedInTheWeek { get; set; }

        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<CnssDeclarationSession> CnssDeclarationSession { get; set; }
        public virtual ICollection<Payslip> Payslip { get; set; }
        public virtual ICollection<SessionBonus> SessionBonus { get; set; }
        public virtual ICollection<SessionContract> SessionContract { get; set; }
        public virtual ICollection<SessionLoanInstallment> SessionLoanInstallment { get; set; }
        public virtual ICollection<TransferOrderSession> TransferOrderSession { get; set; }
    }
}