// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Settlement
    {
        public Settlement()
        {
            ReflectiveSettlementIdGapSettlementNavigation = new HashSet<ReflectiveSettlement>();
            ReflectiveSettlementIdSettlementNavigation = new HashSet<ReflectiveSettlement>();
            SettlementCommitment = new HashSet<SettlementCommitment>();
            SettlementDocumentWithholdingTax = new HashSet<SettlementDocumentWithholdingTax>();
        }

        public int Id { get; set; }
        public int IdTiers { get; set; }
        public DateTime SettlementDate { get; set; }
        public int IdPaymentMethod { get; set; }
        public double? Amount { get; set; }
        public double AmountWithCurrency { get; set; }
        public double? ResidualAmount { get; set; }
        public double? ResidualAmountWithCurrency { get; set; }
        public int? IdStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? IdUsedCurrency { get; set; }
        public double? ExchangeRate { get; set; }
        public string AttachmentUrl { get; set; }
        public string SettlementReference { get; set; }
        public int? IdBankAccount { get; set; }
        public int Direction { get; set; }
        public string Code { get; set; }
        public string IssuingBank { get; set; }
        public string Holder { get; set; }
        public int Type { get; set; }
        public DateTime? CommitmentDate { get; set; }
        public bool IsAccounted { get; set; }
        public int? IdPaymentStatus { get; set; }
        public bool HasBeenReplaced { get; set; }
        public double? WithholdingTax { get; set; }
        public int? IdPaymentSlip { get; set; }
        public string WithholdingTaxAttachmentUrl { get; set; }
        public string Label { get; set; }
        public int? IdReconciliation { get; set; }
        public int? IdSessionCash { get; set; }
        public bool? IsDepositSettlement { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual PaymentMethod IdPaymentMethodNavigation { get; set; }
        public virtual PaymentSlip IdPaymentSlipNavigation { get; set; }
        public virtual PaymentStatus IdPaymentStatusNavigation { get; set; }
        public virtual Reconciliation IdReconciliationNavigation { get; set; }
        public virtual SessionCash IdSessionCashNavigation { get; set; }
        public virtual DocumentStatus IdStatusNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual Currency IdUsedCurrencyNavigation { get; set; }
        public virtual ICollection<ReflectiveSettlement> ReflectiveSettlementIdGapSettlementNavigation { get; set; }
        public virtual ICollection<ReflectiveSettlement> ReflectiveSettlementIdSettlementNavigation { get; set; }
        public virtual ICollection<SettlementCommitment> SettlementCommitment { get; set; }
        public virtual ICollection<SettlementDocumentWithholdingTax> SettlementDocumentWithholdingTax { get; set; }
    }
}