// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SettlementType
    {
        public SettlementType()
        {
            DetailsSettlementMode = new HashSet<DetailsSettlementMode>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<DetailsSettlementMode> DetailsSettlementMode { get; set; }
    }
}