// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SettlementCommitment
    {
        public int Id { get; set; }
        public int CommitmentId { get; set; }
        public int SettlementId { get; set; }
        public double? AssignedAmount { get; set; }
        public double? AssignedAmountWithCurrency { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? Direction { get; set; }
        public double? ExchangeRate { get; set; }
        public double? AssignedWithholdingTax { get; set; }
        public double? AssignedWithholdingTaxWithCurrency { get; set; }

        public virtual FinancialCommitment Commitment { get; set; }
        public virtual Settlement Settlement { get; set; }
    }
}