// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SettlementDocumentWithholdingTax
    {
        public int Id { get; set; }
        public int IdSettlement { get; set; }
        public int IdDocumentWithholdingTax { get; set; }
        public double? AssignedWithholdingTax { get; set; }
        public double AssignedWithholdingTaxWithCurrency { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public double? TotalAmount { get; set; }
        public double TotalAmountWithCurrency { get; set; }

        public virtual DocumentWithholdingTax IdDocumentWithholdingTaxNavigation { get; set; }
        public virtual Settlement IdSettlementNavigation { get; set; }
    }
}