// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SharedDocument
    {
        public int Id { get; set; }
        public DateTime SubmissionDate { get; set; }
        public string AttachmentUrl { get; set; }
        public int IdEmployee { get; set; }
        public int? IdType { get; set; }
        public int? TransactionUserId { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual DocumentRequestType IdTypeNavigation { get; set; }
        public virtual User TransactionUser { get; set; }
    }
}