// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Shelf
    {
        public Shelf()
        {
            ItemWarehouse = new HashSet<ItemWarehouse>();
            Storage = new HashSet<Storage>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdWharehouse { get; set; }
        public bool? IsDefault { get; set; }

        public virtual Warehouse IdWharehouseNavigation { get; set; }
        public virtual ICollection<ItemWarehouse> ItemWarehouse { get; set; }
        public virtual ICollection<Storage> Storage { get; set; }
    }
}