// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Skills
    {
        public Skills()
        {
            EmployeeSkills = new HashSet<EmployeeSkills>();
            ExternalTrainerSkills = new HashSet<ExternalTrainerSkills>();
            JobSkills = new HashSet<JobSkills>();
            RecruitmentSkills = new HashSet<RecruitmentSkills>();
            ReviewSkills = new HashSet<ReviewSkills>();
            TrainingExpectedSkills = new HashSet<TrainingExpectedSkills>();
            TrainingRequiredSkills = new HashSet<TrainingRequiredSkills>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int? IdFamily { get; set; }

        public virtual SkillsFamily IdFamilyNavigation { get; set; }
        public virtual ICollection<EmployeeSkills> EmployeeSkills { get; set; }
        public virtual ICollection<ExternalTrainerSkills> ExternalTrainerSkills { get; set; }
        public virtual ICollection<JobSkills> JobSkills { get; set; }
        public virtual ICollection<RecruitmentSkills> RecruitmentSkills { get; set; }
        public virtual ICollection<ReviewSkills> ReviewSkills { get; set; }
        public virtual ICollection<TrainingExpectedSkills> TrainingExpectedSkills { get; set; }
        public virtual ICollection<TrainingRequiredSkills> TrainingRequiredSkills { get; set; }
    }
}