// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SourceDeduction
    {
        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public int Year { get; set; }
        public int Status { get; set; }
        public double TaxableWages { get; set; }
        public double NaturalAdvantage { get; set; }
        public double GrossTaxable { get; set; }
        public double RetainedReinvested { get; set; }
        public double SumIrpp { get; set; }
        public double Css { get; set; }
        public double NetToPay { get; set; }
        public int IdSourceDeductionSession { get; set; }
        public int IdEmployee { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual SourceDeductionSession IdSourceDeductionSessionNavigation { get; set; }
    }
}