// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SourceDeductionSession
    {
        public SourceDeductionSession()
        {
            SourceDeduction = new HashSet<SourceDeduction>();
            SourceDeductionSessionEmployee = new HashSet<SourceDeductionSessionEmployee>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreationDate { get; set; }
        public int Year { get; set; }
        public int State { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }

        public virtual ICollection<SourceDeduction> SourceDeduction { get; set; }
        public virtual ICollection<SourceDeductionSessionEmployee> SourceDeductionSessionEmployee { get; set; }
    }
}