// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class StockMovement
    {
        public int Id { get; set; }
        public int? IdDocumentLine { get; set; }
        public int? IdStockDocumentLine { get; set; }
        public int? IdItem { get; set; }
        public int IdWarehouse { get; set; }
        public DateTime? CreationDate { get; set; }
        public double? RealStock { get; set; }
        public double? MovementQty { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public double? Cump { get; set; }
        public string Operation { get; set; }
        public string Status { get; set; }
        public string DeletedToken { get; set; }
        public int? IdClaim { get; set; }

        public virtual Claim IdClaimNavigation { get; set; }
        public virtual DocumentLine IdDocumentLineNavigation { get; set; }
        public virtual Item IdItemNavigation { get; set; }
        public virtual StockDocumentLine IdStockDocumentLineNavigation { get; set; }
        public virtual Warehouse IdWarehouseNavigation { get; set; }
    }
}