// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class StockDocumentType
    {
        public StockDocumentType()
        {
            StockDocument = new HashSet<StockDocument>();
        }

        public string CodeType { get; set; }
        public string Type { get; set; }
        public string StockOperation { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<StockDocument> StockDocument { get; set; }
    }
}