// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class StockDocument
    {
        public StockDocument()
        {
            StockDocumentLine = new HashSet<StockDocumentLine>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string TypeStockDocument { get; set; }
        public int? IdWarehouseSource { get; set; }
        public int? IdWarehouseDestination { get; set; }
        public int? IdDocumentStatus { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? ValidationDate { get; set; }
        public string Reference { get; set; }
        public string Informations { get; set; }
        public bool IsPlannedInventory { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdTiers { get; set; }
        public string Shelf { get; set; }
        public int? IdUser { get; set; }
        public int? IdInputUser1 { get; set; }
        public int? IdInputUser2 { get; set; }
        public bool? IsDefaultValue { get; set; }
        public bool? IsOnlyAvailableQuantity { get; set; }
        public int? IdStorageSource { get; set; }
        public int? IdStorageDestination { get; set; }
        public string TransferType { get; set; }

        public virtual DocumentStatus IdDocumentStatusNavigation { get; set; }
        public virtual User IdInputUser1Navigation { get; set; }
        public virtual User IdInputUser2Navigation { get; set; }
        public virtual Storage IdStorageDestinationNavigation { get; set; }
        public virtual Storage IdStorageSourceNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual Warehouse IdWarehouseDestinationNavigation { get; set; }
        public virtual Warehouse IdWarehouseSourceNavigation { get; set; }
        public virtual StockDocumentType TypeStockDocumentNavigation { get; set; }
        public virtual ICollection<StockDocumentLine> StockDocumentLine { get; set; }
    }
}