// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Storage
    {
        public Storage()
        {
            DocumentLine = new HashSet<DocumentLine>();
            ItemWarehouse = new HashSet<ItemWarehouse>();
            StockDocumentIdStorageDestinationNavigation = new HashSet<StockDocument>();
            StockDocumentIdStorageSourceNavigation = new HashSet<StockDocument>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdShelf { get; set; }
        public bool? IsDefault { get; set; }
        public int? IdResponsable { get; set; }

        public virtual User IdResponsableNavigation { get; set; }
        public virtual Shelf IdShelfNavigation { get; set; }
        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<ItemWarehouse> ItemWarehouse { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdStorageDestinationNavigation { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdStorageSourceNavigation { get; set; }
    }
}