// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class SubFamily
    {
        public SubFamily()
        {
            Item = new HashSet<Item>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public int IdFamily { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public string UrlPicture { get; set; }
        public int? IdSubCategoryEcommerce { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Family IdFamilyNavigation { get; set; }
        public virtual ICollection<Item> Item { get; set; }
    }
}