// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TaxeGroupTiersConfig
    {
        public int Id { get; set; }
        public int IdTaxeGroupTiers { get; set; }
        public int IdTaxe { get; set; }
        public double Value { get; set; }
        public int TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual TaxeGroupTiers IdTaxeGroupTiersNavigation { get; set; }
        public virtual Taxe IdTaxeNavigation { get; set; }
    }
}