// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Taxe
    {
        public Taxe()
        {
            Company = new HashSet<Company>();
            DocumentExpenseLine = new HashSet<DocumentExpenseLine>();
            DocumentLineTaxe = new HashSet<DocumentLineTaxe>();
            DocumentTaxsResume = new HashSet<DocumentTaxsResume>();
            Expense = new HashSet<Expense>();
            Project = new HashSet<Project>();
            TaxeGroupTiersConfig = new HashSet<TaxeGroupTiersConfig>();
            TaxeItem = new HashSet<TaxeItem>();
        }

        public int Id { get; set; }
        public string Label { get; set; }
        public string CodeTaxe { get; set; }
        public double? TaxeValue { get; set; }
        public int? IdTaxeType { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int TaxeType { get; set; }
        public int? IdAccountingAccountSales { get; set; }
        public int? IdAccountingAccountPurchase { get; set; }
        public bool IsCalculable { get; set; }

        public virtual TaxeType IdTaxeTypeNavigation { get; set; }
        public virtual ICollection<Company> Company { get; set; }
        public virtual ICollection<DocumentExpenseLine> DocumentExpenseLine { get; set; }
        public virtual ICollection<DocumentLineTaxe> DocumentLineTaxe { get; set; }
        public virtual ICollection<DocumentTaxsResume> DocumentTaxsResume { get; set; }
        public virtual ICollection<Expense> Expense { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<TaxeGroupTiersConfig> TaxeGroupTiersConfig { get; set; }
        public virtual ICollection<TaxeItem> TaxeItem { get; set; }
    }
}