// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TaxeType
    {
        public TaxeType()
        {
            Taxe = new HashSet<Taxe>();
        }

        public int Id { get; set; }
        public string TaxeTypeCode { get; set; }
        public string Description { get; set; }
        public int? IdTaxeTypeCalculation { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<Taxe> Taxe { get; set; }
    }
}