// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Team
    {
        public Team()
        {
            EmployeeTeam = new HashSet<EmployeeTeam>();
        }

        public int Id { get; set; }
        public string TeamCode { get; set; }
        public string Name { get; set; }
        public DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdDepartment { get; set; }
        public int IdManager { get; set; }
        public bool State { get; set; }
        public int? NumberOfAffected { get; set; }
        public int? IdTeamType { get; set; }

        public virtual Department IdDepartmentNavigation { get; set; }
        public virtual Employee IdManagerNavigation { get; set; }
        public virtual TeamType IdTeamTypeNavigation { get; set; }
        public virtual ICollection<EmployeeTeam> EmployeeTeam { get; set; }
    }
}