// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TicketPayment
    {
        public int Id { get; set; }
        public DateTime CreationDate { get; set; }
        public int IdTicket { get; set; }
        public int IdPaymentType { get; set; }
        public double Amount { get; set; }
        public double? ReceivedAmount { get; set; }
        public double? AmountReturned { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? Status { get; set; }

        public virtual PaymentType IdPaymentTypeNavigation { get; set; }
        public virtual Ticket IdTicketNavigation { get; set; }
    }
}