// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Ticket
    {
        public Ticket()
        {
            TicketPayment = new HashSet<TicketPayment>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public DateTime CreationDate { get; set; }
        public int Status { get; set; }
        public int IdDeliveryForm { get; set; }
        public int IdSessionCash { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdInvoice { get; set; }

        public virtual Document IdDeliveryFormNavigation { get; set; }
        public virtual Document IdInvoiceNavigation { get; set; }
        public virtual SessionCash IdSessionCashNavigation { get; set; }
        public virtual ICollection<TicketPayment> TicketPayment { get; set; }
    }
}