// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistence.Entities
{
    public partial class Tiers
    {
        public Tiers()
        {
            Address = new HashSet<Address>();
            ClaimIdClientNavigation = new HashSet<Claim>();
            ClaimIdFournisseurNavigation = new HashSet<Claim>();
            Contact = new HashSet<Contact>();
            DateToRemember = new HashSet<DateToRemember>();
            Document = new HashSet<Document>();
            DocumentExpenseLine = new HashSet<DocumentExpenseLine>();
            FinancialCommitment = new HashSet<FinancialCommitment>();
            ItemTiers = new HashSet<ItemTiers>();
            PriceRequestDetail = new HashSet<PriceRequestDetail>();
            Project = new HashSet<Project>();
            ProvisioningDetails = new HashSet<ProvisioningDetails>();
            ReceiptSpent = new HashSet<ReceiptSpent>();
            SearchItem = new HashSet<SearchItem>();
            Settlement = new HashSet<Settlement>();
            StockDocument = new HashSet<StockDocument>();
            TiersPrices = new HashSet<TiersPrices>();
            TiersProvisioning = new HashSet<TiersProvisioning>();
            Timetable = new HashSet<Timetable>();
            Training = new HashSet<Training>();
            User = new HashSet<User>();
            UsersBtob = new HashSet<UsersBtob>();
            Vehicle = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public int? IdLegalForme { get; set; }
        public int? IdPaymentCondition { get; set; }
        public int IdTypeTiers { get; set; }
        public int? IdCity { get; set; }
        public int? IdCountry { get; set; }
        public string CodeTiers { get; set; }
        public string Name { get; set; }
        public byte[] Logo { get; set; }
        public string Adress { get; set; }
        public string Region { get; set; }
        public double? AuthorizedSettlement { get; set; }
        public int? Status { get; set; }
        public string Rib { get; set; }
        public string Cin { get; set; }
        public double? Discount { get; set; }
        public string MatriculeFiscale { get; set; }
        public int? IdPaymentMethod { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdAccountingAccountTiers { get; set; }
        public string CounterPartyAccount { get; set; }
        public string CommercialRegister { get; set; }
        public string Cp { get; set; }
        public double? AuthorizedAmountOrder { get; set; }
        public double? AuthorizedAmountDelivery { get; set; }
        public double? AuthorizedAmountInvoice { get; set; }
        public int? IdTaxeGroupTiers { get; set; }
        public int? IdCurrency { get; set; }
        public string DeletedToken { get; set; }
        public int? DeleveryDelay { get; set; }
        public int? PaymentDelay { get; set; }
        public bool? IsCash { get; set; }
        public int? IdEcommerceCustomer { get; set; }
        public double? ProvisionalAuthorizedAmountDelivery { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Linkedin { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Description { get; set; }
        public string MapLocalisation { get; set; }
        public string UrlPicture { get; set; }
        public string ActivitySector { get; set; }
        public string LeadSource { get; set; }
        public int? IdPhone { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? IdSettlementMode { get; set; }
        public int? IdDeliveryType { get; set; }
        public int? TiersClassification { get; set; }
        public bool WasLead { get; set; }
        public int? IdSalesPrice { get; set; }
        public int? IdTierCategory { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsSynchronizedBtoB { get; set; }

        public virtual City IdCityNavigation { get; set; }
        public virtual Country IdCountryNavigation { get; set; }
        public virtual Currency IdCurrencyNavigation { get; set; }
        public virtual PaymentCondition IdPaymentConditionNavigation { get; set; }
        public virtual Phone IdPhoneNavigation { get; set; }
        public virtual SalesPrice IdSalesPriceNavigation { get; set; }
        public virtual SettlementMode IdSettlementModeNavigation { get; set; }
        public virtual TaxeGroupTiers IdTaxeGroupTiersNavigation { get; set; }
        public virtual TierCategory IdTierCategoryNavigation { get; set; }
        public virtual TypeTiers IdTypeTiersNavigation { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Claim> ClaimIdClientNavigation { get; set; }
        public virtual ICollection<Claim> ClaimIdFournisseurNavigation { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<DateToRemember> DateToRemember { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<DocumentExpenseLine> DocumentExpenseLine { get; set; }
        public virtual ICollection<FinancialCommitment> FinancialCommitment { get; set; }
        public virtual ICollection<ItemTiers> ItemTiers { get; set; }
        public virtual ICollection<PriceRequestDetail> PriceRequestDetail { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<ProvisioningDetails> ProvisioningDetails { get; set; }
        public virtual ICollection<ReceiptSpent> ReceiptSpent { get; set; }
        public virtual ICollection<SearchItem> SearchItem { get; set; }
        public virtual ICollection<Settlement> Settlement { get; set; }
        public virtual ICollection<StockDocument> StockDocument { get; set; }
        public virtual ICollection<TiersPrices> TiersPrices { get; set; }
        public virtual ICollection<TiersProvisioning> TiersProvisioning { get; set; }
        public virtual ICollection<Timetable> Timetable { get; set; }
        public virtual ICollection<Training> Training { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<UsersBtob> UsersBtob { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}