// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TierCategory
    {
        public TierCategory()
        {
            Tiers = new HashSet<Tiers>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Tiers> Tiers { get; set; }
    }
}