// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TimeSheet
    {
        public TimeSheet()
        {
            BillingEmployee = new HashSet<BillingEmployee>();
            TimeSheetLine = new HashSet<TimeSheetLine>();
        }

        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public DateTime Month { get; set; }
        public DateTime CreationDate { get; set; }
        public int Status { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int? IdEmployeeTreated { get; set; }
        public string AttachementFile { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Employee IdEmployeeTreatedNavigation { get; set; }
        public virtual ICollection<BillingEmployee> BillingEmployee { get; set; }
        public virtual ICollection<TimeSheetLine> TimeSheetLine { get; set; }
    }
}