// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TimeSheetLine
    {
        public int Id { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public int? IdProject { get; set; }
        public DateTime Day { get; set; }
        public int IdTimeSheet { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Details { get; set; }
        public bool Valid { get; set; }
        public int? IdDayOff { get; set; }
        public int? IdLeave { get; set; }
        public bool? Worked { get; set; }

        public virtual DayOff IdDayOffNavigation { get; set; }
        public virtual Leave IdLeaveNavigation { get; set; }
        public virtual Project IdProjectNavigation { get; set; }
        public virtual TimeSheet IdTimeSheetNavigation { get; set; }
    }
}