// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Training
    {
        public Training()
        {
            TrainingByEmployee = new HashSet<TrainingByEmployee>();
            TrainingExpectedSkills = new HashSet<TrainingExpectedSkills>();
            TrainingRequest = new HashSet<TrainingRequest>();
            TrainingRequiredSkills = new HashSet<TrainingRequiredSkills>();
            TrainingSession = new HashSet<TrainingSession>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double? Duration { get; set; }
        public bool IsCertified { get; set; }
        public bool IsInternal { get; set; }
        public int? IdSupplier { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string TrainingPictureUrl { get; set; }

        public virtual Tiers IdSupplierNavigation { get; set; }
        public virtual ICollection<TrainingByEmployee> TrainingByEmployee { get; set; }
        public virtual ICollection<TrainingExpectedSkills> TrainingExpectedSkills { get; set; }
        public virtual ICollection<TrainingRequest> TrainingRequest { get; set; }
        public virtual ICollection<TrainingRequiredSkills> TrainingRequiredSkills { get; set; }
        public virtual ICollection<TrainingSession> TrainingSession { get; set; }
    }
}