// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingSession
    {
        public TrainingSession()
        {
            EmployeeTrainingSession = new HashSet<EmployeeTrainingSession>();
            ExternalTraining = new HashSet<ExternalTraining>();
            TrainingRequest = new HashSet<TrainingRequest>();
            TrainingSeance = new HashSet<TrainingSeance>();
        }

        public int Id { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdTraining { get; set; }
        public string Name { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Description { get; set; }
        public string SessionPlan { get; set; }
        public double? Duration { get; set; }
        public string SessionPlanUrl { get; set; }
        public int? IdExternalTrainer { get; set; }
        public int? IdEmployee { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual ExternalTrainer IdExternalTrainerNavigation { get; set; }
        public virtual Training IdTrainingNavigation { get; set; }
        public virtual ICollection<EmployeeTrainingSession> EmployeeTrainingSession { get; set; }
        public virtual ICollection<ExternalTraining> ExternalTraining { get; set; }
        public virtual ICollection<TrainingRequest> TrainingRequest { get; set; }
        public virtual ICollection<TrainingSeance> TrainingSeance { get; set; }
    }
}