// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingCenterRoom
    {
        public TrainingCenterRoom()
        {
            ExternalTraining = new HashSet<ExternalTraining>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Capacity { get; set; }
        public int? Availability { get; set; }
        public int? RoomType { get; set; }
        public double? RentPerHour { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdTrainingCenter { get; set; }

        public virtual TrainingCenter IdTrainingCenterNavigation { get; set; }
        public virtual ICollection<ExternalTraining> ExternalTraining { get; set; }
    }
}