// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingCenter
    {
        public TrainingCenter()
        {
            TrainingCenterRoom = new HashSet<TrainingCenterRoom>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public TimeSpan? OpeningTime { get; set; }
        public TimeSpan? ClosingTime { get; set; }
        public int? ModeOfPayment { get; set; }
        public string CenterPhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdTrainingCenterManager { get; set; }

        public virtual TrainingCenterManager IdTrainingCenterManagerNavigation { get; set; }
        public virtual ICollection<TrainingCenterRoom> TrainingCenterRoom { get; set; }
    }
}