// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingSeance
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public TimeSpan StartHour { get; set; }
        public TimeSpan EndHour { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdTrainingSession { get; set; }
        public string Details { get; set; }
        public int? DayOfWeek { get; set; }

        public virtual TrainingSession IdTrainingSessionNavigation { get; set; }
    }
}