// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingCenterManager
    {
        public TrainingCenterManager()
        {
            TrainingCenter = new HashSet<TrainingCenter>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual ICollection<TrainingCenter> TrainingCenter { get; set; }
    }
}