// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TrainingRequest
    {
        public int Id { get; set; }
        public DateTime? ExpectedDate { get; set; }
        public int Status { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? TreatmentDate { get; set; }
        public int IdTraining { get; set; }
        public int IdEmployeeAuthor { get; set; }
        public int IdEmployeeCollaborator { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Description { get; set; }
        public int? IdTrainingSession { get; set; }

        public virtual Employee IdEmployeeAuthorNavigation { get; set; }
        public virtual Employee IdEmployeeCollaboratorNavigation { get; set; }
        public virtual Training IdTrainingNavigation { get; set; }
        public virtual TrainingSession IdTrainingSessionNavigation { get; set; }
    }
}