// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TransferOrderDetails
    {
        public int Id { get; set; }
        public string Rib { get; set; }
        public double Amount { get; set; }
        public int IdTransferOrder { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdEmployee { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual TransferOrder IdTransferOrderNavigation { get; set; }
    }
}