// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class TransferOrder
    {
        public TransferOrder()
        {
            Payslip = new HashSet<Payslip>();
            TransferOrderDetails = new HashSet<TransferOrderDetails>();
            TransferOrderSession = new HashSet<TransferOrderSession>();
        }

        public int Id { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int IdBankAccount { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime Month { get; set; }
        public string Title { get; set; }
        public double TotalAmount { get; set; }
        public string Code { get; set; }
        public int State { get; set; }

        public virtual BankAccount IdBankAccountNavigation { get; set; }
        public virtual ICollection<Payslip> Payslip { get; set; }
        public virtual ICollection<TransferOrderDetails> TransferOrderDetails { get; set; }
        public virtual ICollection<TransferOrderSession> TransferOrderSession { get; set; }
    }
}