// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class UserDiscussionChat
    {
        public UserDiscussionChat()
        {
            MessageChat = new HashSet<MessageChat>();
        }

        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdDiscussion { get; set; }
        public bool HasNotif { get; set; }

        public virtual Discussion IdDiscussionNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual ICollection<MessageChat> MessageChat { get; set; }
    }
}