// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class UserInfo
    {
        public int IdUserInfo { get; set; }
        public int IdUser { get; set; }
        public int IdInformation { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual Information IdInformationNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
    }
}