// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistence.Entities
{
    public partial class UserWarehouse
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string UserMail { get; set; }
        public int? IdWarehouse { get; set; }

        public virtual Warehouse IdWarehouseNavigation { get; set; }
    }
}