// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class UserFileAccess
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdFile { get; set; }
        public bool ReadFile { get; set; }
        public bool WriteFile { get; set; }
        public int? TransactionUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }

        public virtual FileDrive IdFileNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
    }
}