// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Persistence.Entities
{
    public partial class UsersBtob
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public string TransactionUserEmail { get; set; }
        public string FullName { get; set; }
        public int IdClient { get; set; }

        public virtual Tiers IdClientNavigation { get; set; }
    }
}