// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    /// <summary>
    /// Table contains list of the users
    /// </summary>
    public partial class User
    {
        public User()
        {
            Candidate = new HashSet<Candidate>();
            CashRegister = new HashSet<CashRegister>();
            DocumentIdCreatorNavigation = new HashSet<Document>();
            DocumentIdValidatorNavigation = new HashSet<Document>();
            DocumentLineNegotiationOptions = new HashSet<DocumentLineNegotiationOptions>();
            FileDrive = new HashSet<FileDrive>();
            FileDriveSharedDocument = new HashSet<FileDriveSharedDocument>();
            FundsTransfer = new HashSet<FundsTransfer>();
            InverseIdUserParentNavigation = new HashSet<User>();
            MobilityRequest = new HashSet<MobilityRequest>();
            NewUserEmail = new HashSet<NewUserEmail>();
            Note = new HashSet<Note>();
            PurchaseSettings = new HashSet<PurchaseSettings>();
            SearchItem = new HashSet<SearchItem>();
            SessionCash = new HashSet<SessionCash>();
            SharedDocument = new HashSet<SharedDocument>();
            StockDocumentIdInputUser1Navigation = new HashSet<StockDocument>();
            StockDocumentIdInputUser2Navigation = new HashSet<StockDocument>();
            StockDocumentIdUserNavigation = new HashSet<StockDocument>();
            Storage = new HashSet<Storage>();
            UserDiscussionChat = new HashSet<UserDiscussionChat>();
            UserFileAccess = new HashSet<UserFileAccess>();
            UserFileModification = new HashSet<UserFileModification>();
            UserInfo = new HashSet<UserInfo>();
            UserPrivilege = new HashSet<UserPrivilege>();
            Warehouse = new HashSet<Warehouse>();
        }

        /// <summary>
        /// Unique identifier
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// FIrst name of user
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// Last name of user
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// Login of user
        /// </summary>
        public string Login { get; set; }
        /// <summary>
        /// Password of user
        /// </summary>
        public string Password { get; set; }
        public string Token { get; set; }
        /// <summary>
        /// Phone number
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// Work phone number
        /// </summary>
        public string WorkPhone { get; set; }
        /// <summary>
        /// Mobile phone numer
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// Email of user
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Day birth user
        /// </summary>
        public DateTime? Birthday { get; set; }
        /// <summary>
        /// Picture of user
        /// </summary>
        public byte[] Picture { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int? IdUserParent { get; set; }
        public string Lang { get; set; }
        public int? IdEmployee { get; set; }
        public bool? IsBtoB { get; set; }
        public int? IdTiers { get; set; }
        public string Role { get; set; }
        public bool? IsTecDoc { get; set; }
        public bool? IsActif { get; set; }
        public DateTime? LastConnection { get; set; }
        public string LastConnectedIpAdress { get; set; }
        public string Twitter { get; set; }
        public string Linkedin { get; set; }
        public string Fax { get; set; }
        public string Facebook { get; set; }
        public bool? IsWithEmailNotification { get; set; }
        public int? IdPhone { get; set; }
        public string UrlPicture { get; set; }
        public string FullName { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
        public virtual Phone IdPhoneNavigation { get; set; }
        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual User IdUserParentNavigation { get; set; }
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<CashRegister> CashRegister { get; set; }
        public virtual ICollection<Document> DocumentIdCreatorNavigation { get; set; }
        public virtual ICollection<Document> DocumentIdValidatorNavigation { get; set; }
        public virtual ICollection<DocumentLineNegotiationOptions> DocumentLineNegotiationOptions { get; set; }
        public virtual ICollection<FileDrive> FileDrive { get; set; }
        public virtual ICollection<FileDriveSharedDocument> FileDriveSharedDocument { get; set; }
        public virtual ICollection<FundsTransfer> FundsTransfer { get; set; }
        public virtual ICollection<User> InverseIdUserParentNavigation { get; set; }
        public virtual ICollection<MobilityRequest> MobilityRequest { get; set; }
        public virtual ICollection<NewUserEmail> NewUserEmail { get; set; }
        public virtual ICollection<Note> Note { get; set; }
        public virtual ICollection<PurchaseSettings> PurchaseSettings { get; set; }
        public virtual ICollection<SearchItem> SearchItem { get; set; }
        public virtual ICollection<SessionCash> SessionCash { get; set; }
        public virtual ICollection<SharedDocument> SharedDocument { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdInputUser1Navigation { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdInputUser2Navigation { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdUserNavigation { get; set; }
        public virtual ICollection<Storage> Storage { get; set; }
        public virtual ICollection<UserDiscussionChat> UserDiscussionChat { get; set; }
        public virtual ICollection<UserFileAccess> UserFileAccess { get; set; }
        public virtual ICollection<UserFileModification> UserFileModification { get; set; }
        public virtual ICollection<UserInfo> UserInfo { get; set; }
        public virtual ICollection<UserPrivilege> UserPrivilege { get; set; }
        public virtual ICollection<Warehouse> Warehouse { get; set; }
    }
}