// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class VariableValidityPeriod
    {
        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public string Formule { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public int IdVariable { get; set; }
        public int? State { get; set; }

        public virtual Variable IdVariableNavigation { get; set; }
    }
}