// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            Document = new HashSet<Document>();
        }

        public int Id { get; set; }
        public int? IdTiers { get; set; }
        public int? IdVehicleBrand { get; set; }
        public int? IdVehicleModel { get; set; }
        public int? IdVehicleEnergy { get; set; }
        public string RegistrationNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string Power { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? TransactionUserId { get; set; }

        public virtual Tiers IdTiersNavigation { get; set; }
        public virtual VehicleBrand IdVehicleBrandNavigation { get; set; }
        public virtual VehicleEnergy IdVehicleEnergyNavigation { get; set; }
        public virtual ModelOfItem IdVehicleModelNavigation { get; set; }
        public virtual ICollection<Document> Document { get; set; }
    }
}