// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class VehicleBrand
    {
        public VehicleBrand()
        {
            ItemVehicleBrandModelSubModel = new HashSet<ItemVehicleBrandModelSubModel>();
            ModelOfItem = new HashSet<ModelOfItem>();
            OemItem = new HashSet<OemItem>();
            Vehicle = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public string DeletedToken { get; set; }
        public bool IsDeleted { get; set; }
        public string UrlPicture { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual ICollection<ItemVehicleBrandModelSubModel> ItemVehicleBrandModelSubModel { get; set; }
        public virtual ICollection<ModelOfItem> ModelOfItem { get; set; }
        public virtual ICollection<OemItem> OemItem { get; set; }
        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}