// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class VehicleEnergy
    {
        public VehicleEnergy()
        {
            Vehicle = new HashSet<Vehicle>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedToken { get; set; }
        public int? TransactionUserId { get; set; }

        public virtual ICollection<Vehicle> Vehicle { get; set; }
    }
}