// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class Warehouse
    {
        public Warehouse()
        {
            Active = new HashSet<Active>();
            CashRegister = new HashSet<CashRegister>();
            Claim = new HashSet<Claim>();
            DocumentLine = new HashSet<DocumentLine>();
            InverseIdWarehouseParentNavigation = new HashSet<Warehouse>();
            ItemWarehouse = new HashSet<ItemWarehouse>();
            Shelf = new HashSet<Shelf>();
            StockDocumentIdWarehouseDestinationNavigation = new HashSet<StockDocument>();
            StockDocumentIdWarehouseSourceNavigation = new HashSet<StockDocument>();
            StockDocumentLine = new HashSet<StockDocumentLine>();
            StockMovement = new HashSet<StockMovement>();
            UserWarehouse = new HashSet<UserWarehouse>();
        }

        public int Id { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseAdresse { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public int? IdWarehouseParent { get; set; }
        public string DeletedToken { get; set; }
        public bool IsCentral { get; set; }
        public bool IsWarehouse { get; set; }
        public int? IdResponsable { get; set; }
        public bool IsEcommerce { get; set; }
        public bool ForEcommerceModule { get; set; }
        public int? IdUserResponsable { get; set; }

        public virtual Employee IdResponsableNavigation { get; set; }
        public virtual User IdUserResponsableNavigation { get; set; }
        public virtual Warehouse IdWarehouseParentNavigation { get; set; }
        public virtual ICollection<Active> Active { get; set; }
        public virtual ICollection<CashRegister> CashRegister { get; set; }
        public virtual ICollection<Claim> Claim { get; set; }
        public virtual ICollection<DocumentLine> DocumentLine { get; set; }
        public virtual ICollection<Warehouse> InverseIdWarehouseParentNavigation { get; set; }
        public virtual ICollection<ItemWarehouse> ItemWarehouse { get; set; }
        public virtual ICollection<Shelf> Shelf { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdWarehouseDestinationNavigation { get; set; }
        public virtual ICollection<StockDocument> StockDocumentIdWarehouseSourceNavigation { get; set; }
        public virtual ICollection<StockDocumentLine> StockDocumentLine { get; set; }
        public virtual ICollection<StockMovement> StockMovement { get; set; }
        public virtual ICollection<UserWarehouse> UserWarehouse { get; set; }
    }
}