// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class WithholdingTaxLine
    {
        public int Id { get; set; }
        public int IdWithholdingTax { get; set; }
        public int IdReglement { get; set; }
        public double? AmmountHolding { get; set; }
        public double? NetAmount { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public int? WithholdingTaxLineInt1 { get; set; }
        public int? WithholdingTaxLineInt2 { get; set; }
        public int? WithholdingTaxLineInt3 { get; set; }
        public int? WithholdingTaxLineInt4 { get; set; }
        public int? WithholdingTaxLineInt5 { get; set; }
        public int? WithholdingTaxLineInt6 { get; set; }
        public int? WithholdingTaxLineInt7 { get; set; }
        public int? WithholdingTaxLineInt8 { get; set; }
        public int? WithholdingTaxLineInt9 { get; set; }
        public int? WithholdingTaxLineInt10 { get; set; }
        public bool? WithholdingTaxLineBit1 { get; set; }
        public bool? WithholdingTaxLineBit2 { get; set; }
        public bool? WithholdingTaxLineBit3 { get; set; }
        public bool? WithholdingTaxLineBit4 { get; set; }
        public bool? WithholdingTaxLineBit5 { get; set; }
        public bool? WithholdingTaxLineBit6 { get; set; }
        public bool? WithholdingTaxLineBit7 { get; set; }
        public bool? WithholdingTaxLineBit8 { get; set; }
        public bool? WithholdingTaxLineBit9 { get; set; }
        public bool? WithholdingTaxLineBit10 { get; set; }
        public double? WithholdingTaxLineFloat1 { get; set; }
        public double? WithholdingTaxLineFloat2 { get; set; }
        public double? WithholdingTaxLineFloat3 { get; set; }
        public double? WithholdingTaxLineFloat4 { get; set; }
        public double? WithholdingTaxLineFloat5 { get; set; }
        public double? WithholdingTaxLineFloat6 { get; set; }
        public double? WithholdingTaxLineFloat7 { get; set; }
        public double? WithholdingTaxLineFloat8 { get; set; }
        public double? WithholdingTaxLineFloat9 { get; set; }
        public double? WithholdingTaxLineFloat10 { get; set; }
        public string WithholdingTaxLineVarchar1 { get; set; }
        public string WithholdingTaxLineVarchar2 { get; set; }
        public string WithholdingTaxLineVarchar3 { get; set; }
        public string WithholdingTaxLineVarchar4 { get; set; }
        public string WithholdingTaxLineVarchar5 { get; set; }
        public string WithholdingTaxLineVarchar6 { get; set; }
        public string WithholdingTaxLineVarchar7 { get; set; }
        public string WithholdingTaxLineVarchar8 { get; set; }
        public string WithholdingTaxLineVarchar9 { get; set; }
        public string WithholdingTaxLineVarchar10 { get; set; }
        public DateTime? WithholdingTaxLineDate1 { get; set; }
        public DateTime? WithholdingTaxLineDate2 { get; set; }
        public DateTime? WithholdingTaxLineDate3 { get; set; }
        public DateTime? WithholdingTaxLineDate4 { get; set; }
        public DateTime? WithholdingTaxLineDate5 { get; set; }
        public DateTime? WithholdingTaxLineDate6 { get; set; }
        public DateTime? WithholdingTaxLineDate7 { get; set; }
        public DateTime? WithholdingTaxLineDate8 { get; set; }
        public DateTime? WithholdingTaxLineDate9 { get; set; }
        public DateTime? WithholdingTaxLineDate10 { get; set; }
        public string DeletedToken { get; set; }

        public virtual WithholdingTax IdWithholdingTaxNavigation { get; set; }
    }
}