// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class WithholdingTax
    {
        public WithholdingTax()
        {
            DocumentWithholdingTax = new HashSet<DocumentWithholdingTax>();
            WithholdingTaxLine = new HashSet<WithholdingTaxLine>();
        }

        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int? TransactionUserId { get; set; }
        public string DeletedToken { get; set; }
        public string Code { get; set; }
        public string Designation { get; set; }
        public double Percentage { get; set; }
        public int Type { get; set; }

        public virtual ICollection<DocumentWithholdingTax> DocumentWithholdingTax { get; set; }
        public virtual ICollection<WithholdingTaxLine> WithholdingTaxLine { get; set; }
    }
}