// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Persistence.Entities
{
    public partial class ZipCode
    {
        public ZipCode()
        {
            Address = new HashSet<Address>();
        }

        public int Id { get; set; }
        public string Region { get; set; }
        public string Code { get; set; }
        public int? IdCity { get; set; }
        public bool IsDeleted { get; set; }
        public int TransactionUserId { get; set; }
        public string DeletedToken { get; set; }

        public virtual City IdCityNavigation { get; set; }
        public virtual ICollection<Address> Address { get; set; }
    }
}