/*
Deployment script for Catalog

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/


PRINT N'Creating [Master]...';


GO
CREATE SCHEMA [Master]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [Master].[MasterUser]...';


GO
CREATE TABLE [Master].[MasterUser] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]            NVARCHAR (255) NULL,
    [LastName]             NVARCHAR (255) NULL,
    [Email]                NVARCHAR (255) NULL,
    [Login]                NVARCHAR (255) NULL,
    [Password]             NVARCHAR (255) NULL,
    [Token]                NVARCHAR (MAX) NULL,
    [LastConnectedCompany] NVARCHAR (50)  NULL,
    [IsDeleted]            BIT            NOT NULL,
    [TransactionUserId]    INT            NULL,
    [Deleted_Token]        NVARCHAR (255) NULL,
    CONSTRAINT [PK_MasterUser] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Master].[Company]...';

GO
CREATE TABLE [Master].[MasterDbSettings] (
    [Id]           INT        IDENTITY (1, 1) NOT NULL,
    [Server]       NVARCHAR (MAX) NOT NULL,
    [UserId]       NVARCHAR (MAX) NOT NULL,
    [UserPassword] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_MasterDbSettings] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO
CREATE TABLE [Master].[MasterCompany] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [Code]              NVARCHAR (50)  NULL,
    [Name]              NVARCHAR (255) NULL,
    [Email]             NVARCHAR (255) NULL,
    [IsDeleted]         BIT            NOT NULL,
    [TransactionUserId] INT            NULL,
    [Deleted_Token]     NVARCHAR (255) NULL,
	[DataBaseName]      NVARCHAR (MAX) NOT NULL,
	[IdMasterDbSettings]		INT    NULL,
    CONSTRAINT [PK_MasterCompany] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Master].[UserCompany]...';


GO
CREATE TABLE [Master].[MasterUserCompany] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [IdMasterUser]      INT            NOT NULL,
    [IdMasterCompany]         INT            NOT NULL,
    [IsDeleted]         BIT            NOT NULL,
    [TransactionUserId] INT            NULL,
    [Deleted_Token]     NVARCHAR (255) NULL,
	[IsActif]			BIT NOT NULL  DEFAULT ('true')
    CONSTRAINT [PK_MasterUserCompany] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Master].[FK_UserCompany_Company]...';


GO
ALTER TABLE [Master].[MasterUserCompany] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterUserCompany_MasterCompany] FOREIGN KEY ([IdMasterCompany]) REFERENCES [Master].[MasterCompany] ([Id]);


GO
PRINT N'Creating [Master].[FK_UserCompany_User]...';


GO
ALTER TABLE [Master].[MasterUserCompany] WITH NOCHECK
    ADD CONSTRAINT [FK_MasterUserCompany_MasterUser] FOREIGN KEY ([IdMasterUser]) REFERENCES [Master].[MasterUser] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';

GO
ALTER TABLE [Master].[MasterCompany] WITH NOCHECK
    ADD CONSTRAINT [FK_Company_DbSettings] FOREIGN KEY ([IdMasterDbSettings]) REFERENCES [Master].[MasterDbSettings] ([Id]);

GO

ALTER TABLE [Master].[MasterUserCompany] WITH CHECK CHECK CONSTRAINT [FK_MasterUserCompany_MasterCompany];

ALTER TABLE [Master].[MasterUserCompany] WITH CHECK CHECK CONSTRAINT [FK_MasterUserCompany_MasterUser];

GO
PRINT N'Update complete.';

---Rabeb: add B2B column to MasterUser table: 21/08/2020
GO
ALTER TABLE [Master].[MasterUser]
    ADD [IsBToB] BIT NULL;
	
--- houssem add licen curency  28-08-2020

/****** Object:  Table [Master].[CompanyLicence]    Script Date: 28/08/2020 14:21:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[CompanyLicence](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdMasterCompany] [int] NOT NULL,
	[NombreERPUser] [int] NOT NULL,
	[NombreB2BUser] [int] NOT NULL,
	[ExpirationDate] [date] NULL,
	[IntialDate] [date] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Deleted_Token] [nvarchar](250) NULL,
 CONSTRAINT [PK_CompanyLicence] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Master].[CompanyLicence] ADD  CONSTRAINT [DF_Table_1_NombreOfUser]  DEFAULT ((0)) FOR [NombreERPUser]
GO

ALTER TABLE [Master].[CompanyLicence] ADD  CONSTRAINT [DF_CompanyLicence_NombreB2BUser]  DEFAULT ((0)) FOR [NombreB2BUser]
GO

ALTER TABLE [Master].[CompanyLicence] ADD  CONSTRAINT [DF_CompanyLicence_IntialDate]  DEFAULT (getdate()) FOR [IntialDate]
GO

ALTER TABLE [Master].[CompanyLicence]  WITH CHECK ADD  CONSTRAINT [FK_CompanyLicence_MasterCompany] FOREIGN KEY([IdMasterCompany])
REFERENCES [Master].[MasterCompany] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [Master].[CompanyLicence] CHECK CONSTRAINT [FK_CompanyLicence_MasterCompany]
GO

update Master.MasterUser set IsBToB = 0 where IsBToB is null
alter table Master.MasterUser alter  column IsBToB  bit not null
	
ALTER TABLE [Master].[MasterUser] ADD  CONSTRAINT [DF_MasterUser_IsBToB]  DEFAULT ((0)) FOR [IsBToB]
GO
---Imen chaaben: add GarageDataBaseName column to MasterCompany table: 15/03/2021
GO
ALTER TABLE [Master].[MasterCompany]
      ADD [GarageDataBaseName] [nvarchar](255) NULL;	

