delete  from ERPSettings.RoleConfigByRole 
delete  from ERPSettings.Role where Code not like 'admin%'

INSERT INTO [ERPSettings].[RoleConfigByRole]([IdRoleConfig],[IdRole] ,[IsActive],[IsVisible],[TransactionUserId])
     select Id,1,1,1,Null from [ERPSettings].[RoleConfig] ;
GO

update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 11111
update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 22222
update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 33333
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 44444
update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 77777
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 88888
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100007
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100008
update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 100009
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100099
update ERPSettings.RoleConfigCategory  set Isdeleted = 0where id = 100100
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100200
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100300
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100301
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100302
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100400
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100401
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100402
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100403
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100404
update ERPSettings.RoleConfigCategory  set Isdeleted = 1where id = 100405


update ERPSettings.RoleConfig  set Isdeleted = 0where id = 10155
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 11111
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 22222
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 33333
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 44444
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 70002
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 70003
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 70004
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 70005
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70006
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70007
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70008
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70009
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 70010
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70012
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 70013
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 77777
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 88888
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 90000
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100000
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100001
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100002
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100003
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100004
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100005
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100006
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100007
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100008
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100010
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100011
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100012
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100013
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100014
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100015
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100016
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100017
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100018
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100020
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100021
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100022
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100023
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100024
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100025
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100026
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100027
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100028
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100029
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100030
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100031
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100032
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100033
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100034
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100036
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100037
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100038
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100039
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100041
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100042
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100043
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100044
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100045
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100046
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100047
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100048
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100049
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100051
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100052
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100053
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100054
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100055
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100056
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100057
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 100058
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100059
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100060
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100062
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 100166
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101008
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101009
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101011
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101012
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101013
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101014
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101015
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101016
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101017
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101018
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101019
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101036
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101038
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101039
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101040
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101041
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101042
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101043
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101044
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101045
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101081
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101091
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101092
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 101094
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101100
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101101
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101102
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101103
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 101104
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 102101
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 102102
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 102103
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 102104
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103104
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103105
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103106
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103107
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103108
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103109
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103110
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103111
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103112
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103113
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103114
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103115
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103116
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103117
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103118
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103119
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103120
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103121
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103122
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103123
update ERPSettings.RoleConfig  set Isdeleted = 0where id = 103124
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103125
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103126
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103127
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103128
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103129
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103130
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103131
update ERPSettings.RoleConfig  set Isdeleted = 1where id = 103132
